(function(){var a=function(a,c,d,e,f){this._connectCallback=c;this._deleteCallBack=d;this._newWindowConnectCallback=e;this._callback=f;this.key="bookmarks";this.ready=!1;this._div=a;this._directory={};this._dirObjTypeEnum={connection:1,directory:2};this._createNewDirObject=function(a,b,c,d,e){return{Type:a,Name:b,Value:c,Username:d,Password:e}};this._addToDirectory=function(a,b){try{for(var c=(new Date).getTime();this._directory.hasOwnProperty(c);)c=(new Date).getTime();this._directory[c]=a}catch(d){console.log(d)}};
this._ready=function(a,b,c){try{!0===c&&void 0!==this._callback&&null!==this._callback&&this._callback()}catch(d){console.log(d)}};this.watch("ready",this._ready);this._refreshPanel=function(){try{var a=this.GetBookmarks();this.RefreshBookmarkPanel(a)}catch(b){console.log(b)}};this._save=function(a){try{var b=JSON.stringify(this._directory),c={};c[this.key]=b;"undefined"!==typeof chrome.storage&&chrome.storage.sync.set(c,a);blankNullorUndefined(this._div)||this._refreshPanel()}catch(d){console.log(d)}};
this.MassAddConnections=function(a,b){try{if(0<a.length){for(var c=0;c<a.length;c++){var d=a[c].address,e=a[c].title;if(!this.ConnectionExists(d)){blankNullorUndefined(e)&&(e=d);var f=this._createNewDirObject(this._dirObjTypeEnum.connection,e,d,"","");this._addToDirectory(f)}}this._save(b)}}catch(r){console.log(r)}};this.Populate=function(a){try{var b="";chrome.storage&&"undefined"!==typeof a&&(b=a.bookmarks);blankNullorUndefined(b)||(this._directory=JSON.parse(b));for(key in this._directory)this._directory[key].Type==
this._dirObjTypeEnum.connection&&blankNullorUndefined(this._directory[key].Value)&&!blankNullorUndefined(this._directory[key].Name)&&(this._directory[key].Value=this._directory[key].Name);this._save();this.ready=!0}catch(c){console.log(c)}};this.AddConnection=function(a,b,c,d,e){try{if(!blankNullorUndefined(a)&&!this.ConnectionExists(a)){blankNullorUndefined(b)&&(b=a);var f=this._createNewDirObject(this._dirObjTypeEnum.connection,b,a,d,e);this._addToDirectory(f,c);this._save()}}catch(r){console.log(r)}};
this.DeleteConnection=function(a){try{delete this._directory[a],this._save()}catch(b){console.log(b)}};this.ConnectionExists=function(a){try{var b=!1;if(blankNullorUndefined(a))b=!0;else{var c=this.getConnectionKey(a);blankNullorUndefined(c)||(b=!0)}return b}catch(d){console.log(d)}};this.AddDirectory=function(a,b){try{if(!blankNullorUndefined(address)){var c=this._createNewDirObject(this._dirObjTypeEnum.directory,a,{},"","");this._addToDirectory(c,b);this._save()}}catch(d){console.log(d)}};this.ClearPasswords=
function(){try{if("undefined"!==typeof this._directory)for(key in this._directory)this._directory[key].Password="";this._save()}catch(a){console.log(a)}};this.DeleteDirectory=function(a){try{delete this._directory[a]}catch(b){console.log(b)}};this.GetBookmarks=function(){try{var a=[],b;for(b in this._directory)if(!blankNullorUndefined(this._directory[b].Name)){var c={};c.id=b;c.url=this._directory[b].Value;c.title=this._directory[b].Name;a.push(c)}a.sort(this.SortBookmarks);return a}catch(d){console.log(d)}};
this.SortBookmarks=function(a,b){try{return a.title<b.title?-1:a.title>b.title?1:0}catch(c){console.log(c)}};this.RefreshBookmarkPanel=function(a){try{for(;this._div.lastChild;)this._div.removeChild(this._div.lastChild);if(0<a.length){var b,c;for(b=0;b<a.length;b++){c=a[b];var d=document.createElement("div");d.setAttribute("bookmarkID",c.id);d.setAttribute("bookmarkName",c.title);d.style.whiteSpace="nowrap";d.style.verticalAlign="top";d.style.paddingTop="3px";this._div.appendChild(d);var e=document.createElement("div");
e.style.display="inline";e.style.verticalAlign="top";e.style.paddingLeft="3px";e.style.paddingTop="5px";d.appendChild(e);var f=document.createElement("img");f.src="images/bullet4.png";e.appendChild(f);var r=document.createElement("div");r.style.display="inline";r.style.verticalAlign="top";d.appendChild(r);var q=document.createElement("a");q.setAttribute("href",c.url);q.setAttribute("default",c.url);q.innerText=c.title;q.setAttribute("title","Connect to computer");q.addEventListener("click",this._connectCallback);
r.appendChild(q);var x=document.createElement("div");x.style.display="inline";x.style.verticalAlign="bottom";x.style.cursor="pointer";d.appendChild(x);var t=document.createElement("a");t.setAttribute("href",c.url);t.setAttribute("target","_blank");t.setAttribute("title","Open in new window");t.addEventListener("click",this._newWindowConnectCallback);x.appendChild(t);var m=document.createElement("img");m.src="images/page_new4.gif";t.appendChild(m);var h=document.createElement("div");h.style.display=
"inline";h.style.verticalAlign="bottom";h.style.cursor="pointer";d.appendChild(h);var A=document.createElement("a");A.setAttribute("title","Delete");A.addEventListener("click",this._deleteCallBack);h.appendChild(A);var z=document.createElement("img");z.src="images/action_stop4.gif";A.appendChild(z)}}}catch(v){console.log(v)}};this.getConnectionKey=function(a){try{if(!blankNullorUndefined(a)&&"undefined"!==typeof this._directory)for(key in this._directory){var b=this._directory[key].Value;if(!blankNullorUndefined(b)&&
b.toLowerCase()==a.toLowerCase())return key}return""}catch(c){console.log(c)}};this.getUserNameFromAddress=function(a){try{var b="";if(!blankNullorUndefined(a)){var c=this.getConnectionKey(a);blankNullorUndefined(c)||(b=this._directory[c].UserName)}blankNullorUndefined(b)&&(b="");return b}catch(d){console.log(d)}};this.getPasswordFromAddress=function(a){try{var b="";if(!blankNullorUndefined(a)){var c=this.getConnectionKey(a);blankNullorUndefined(c)||(b=this._directory[c].Password)}blankNullorUndefined(b)&&
(b="");return b}catch(d){console.log(d)}}};document.addEventListener("RDPInit",function(b){try{b.detail.prototype.BookmarkObject=a}catch(c){console.log(c)}})})();
var ID={body:"body",titletext:"titletext",titlefreetrialtext:"titleFreeTrialText",titleOffline:"titleOffline",summary:"summary",summaryMessage:"summaryMessage",rdpObject:"chrome_rdp",prompt:"prompt",black:"black",frame:"frame",home:"home",contents:"contents",mru:"mru",rdpaddress_row:"rdpaddress_row",loader_row:"loading_busy_indicator_row",loader_progress:"loading_busy_indicator_progress",menubutton:"menubutton",sessionMenu:"sessionmenu",session:"session",ssl:"ssl",userControls:"controls",addressDiv:"addressrow",
module:"module",payment:"payment",activate:"activate",activate_google:"activate_google",activate_google_btn:"activate_google_button",activate_google_next:"activate_google_next",activate_username:"activate_username",activate_username_next:"activate_username_next",settings:"settings",settings_label:"settings_label",settings_link:"settings_link",license_label:"license_label",license_link:"license_link",contactus_label:"contactus_label",contactus_link:"contactus_link",fullscreen_label:"fullscreen_label",
fullscreen_link:"fullscreen_link",email_table:"email_table",email_label:"email_label",freeTrial_label:"freeTrial_label",signout_label:"signout_label",signout_link:"signout_link",signin_label:"signin_label",signin_link:"signin_link",signingin_label:"signingin_label",txtCachedDataCompleted:"txtCachedDataCompleted",bookmarks:"bookmarks",addBookmark_link:"addBookmark_link",divBookmark_link:"divBookmark_link",settingsTabs:"settingsTabs",settingsPages:"settingsPages",customScreenSize:"customScreenSize",
menutab:"menutab",simplePopup_message_section:"simplePopup_message_section",popup_contactus:"popup_contactus",popup_email_showlog:"popup_email_showlog",popup_email_log:"popup_email_log",popup_email_log_copytoclipboard:"popup_email_log_copytoclipboard",popup_connecting:"popup_connecting",popup_connecting_busy_indicator:"popup_connecting_busy_indicator",popup_connecting_timeout_message:"popup_connecting_timeout_message",popup_crash:"popup_crash",testCompute_email_link:"testCompute_email_link"},popupIDs=
{popup:"popup",head:"popup_header",body:"popup_body",btnYes:"popup_yes",btnSpacer:"popup_btnSpacer",btnNo:"popup_no",callback:"popup_callback",optional_inputs:"popup_optional_inputs",text1:"popup_text1",password:"popup_password",password_store:"popup_password_store",domain:"popup_domain",refreshlink:"refreshlink",popup_auth_section:"popup_auth_section",popup_auth_link:"popup_auth_link"},cssClass={shown:"shown",hidden:"hidden",busy:"busy",error:"error",mruitem:"mruitem",nodisplay:"nodisplay",button:"kd-button",
homeOutToTop:"homeouttotop",homeOutToTopFinal:"homeouttotopfinal",homeInFromTop:"homeinfromtop",homeInFromTopFinal:"homeinfromtopfinal",homeOutToRight:"homeouttoright",homeOutToRightFinal:"homeouttorightfinal",homeInFromLeft:"homeinfromleft",homeInFromLeftFinal:"homeinfromleftfinal",opacity100:"opacity100",opacity0_slow:"opacity0_slow",opacity50:"opacity50",opacity0:"opacity0",marginbottom50:"marginbottom50",marginbottom60:"marginbottom60",scale0:"scale0",scale100:"scale100",darkgray:"darkgray",notBookmarked:"notBookmarked",
paid:"paid",simplePopup:"simplePopup",simplePopup_show:"simplePopup_show"},input={address:"rdpaddress",menubutton:"menubutton",cnctButton:"button",sessionTab:"tab",ScreenSize:"ddlScreenSize",ScreenDepth:"ddlColors",TimeZone:"ddlTimeZone",payment_checkout:"payment_checkout",Language:"ddlLanguages",Keyboard:"ddlKeyboards",ComputerName:"txtRDPName",SSHTunnel:"cbxSSHTunnel",StorePasswords:"cbxStorePasswords",AllowNonNLAConnections:"CheckboxAllowNonNLAConnections",UseTcpNoDelay:"CheckboxUseTcpNoDelay",
AdminConsole:"cbxAdminConsole",DebugLevel:"ddlDebugLevel",ShowWallpaper:"cbxWallpaper",DisableFullWindowDrag:"cbxDisableFullWindowDrag",DisableMenuAnimations:"cbxDisableMenuAnimations",DisableTheming:"cbxDisableTheming",DisableCursorShadow:"cbxDisableCursorShadow",DisableCursorBlinking:"cbxDisableCursorBlinking",EnableFontSmoothing:"cbxEnableFontSmoothing",EnableDesktopComposition:"cbxEnableDesktopComposition",ScreenWidth:"txtScreenWidth",ScreenHeight:"txtScreenHeight",MigrateButton:"btnMigrateBookmarks",
CertificateSelect:"slctCertificate",CertificateDelete:"btnRemoveCertificates",ClearSSLCache:"btnClearSSLCache",restartButton:"restartButton",submitButton:"submitButton"},uiStrings={cnctEnded:"Your connection to '{0}' has ended.",cnctError:"Chrome RDP could not connect to '{0}'.  Please try again.",entryPrompt:"Enter the computer name or address to connect to:",connect:"Connect",disconnect:"Connect",cancel:"Cancel",connecting:"Attempting to connect...",disconnecting:"Disconnecting...",loading:"Loading...",
pluginError:"Plugin not loaded",hotKeyPessed:"A system key press has been detected. The user menu provides common system key commands.",licensePrompt:"Verifying license...",redirecting:"Redirecting to '{0}'...",redirectURL:""},command={load:"LOAD",connect:"CNCT",socket_connected:"SCNCT",disconnect:"DCNCT",alert:"ALERT",status:"STATUS",error:"ERROR",environment:"ENV",delimeter:"|",delimeterArgs:"\r\n",ssl:"MSSL",sendInputEvents:"sendInputEvents",systemKey:"SYSKEY",comboKey:"COMBOKEY",popup:"POPUP",
popupClose:"POPUP_CLOSE",test:"TEST",standby:"STANDBY",activate:"ACTIVATE",activated:"ACTIVATED",paid:"ACTIVATEPAID",hasnotpaid:"ACTIVATEHASNOTPAID",activate_failed:"ACTIVATEFAILED",freetrial:"ACTIVATEFREETRIAL",licenseSetURL:"LICENSE_URL",licenseUpdate:"LICENSE_UPDATE",licenseOffline:"LICENSE_OFFLINE",clearSSLCache:"CLEARSSLCACHE",redirect:"REDIRECT",retry:"RETRY",clipboard_sync:"CLIPBOARD_SYNC",clipboard_data:"CLIPBOARD_DATA",clipboard_paste:"CLIPBOARD_PASTE",clipboard_formatlist_ok:"CLIPBOARD_FORMATLIST_OK",
certs_request:"REQ_CERTS",cert_delete:"DEL_CERT",authorizing:"AUTHORIZING",authorized:"AUTHORIZED",signout:"SIGNOUT",signin:"SIGNIN",authOpened:"AUTH_OPENED",authClosed:"AUTH_CLOSED",screenEnable:"SCREEN_ENABLE",startedDrawing:"STARTED_DRAW",completedStandby:"COMPLETED_STANDBY",viewScale:"VIEW_SCALE",doCrash:"CRASH"},connectionStatus={loading:-3,error:-2,disconnected:-1,standby:0,disconnecting:1,connecting:2,connected:3,licenceCheck:4,redirecting:5},intervals={input:null,altTab:null,systemKey:null,
connecting:null,connecting_timedout:null},keyCodes={tab:"Tab",shift:"ShiftLeft",ctrl:"ControlLeft",alt:"AltLeft",pause:"Pause",cpsLock:"CapsLock",esc:"Escape",pgup:"PageUp",pgdwn:"PageDown",end:"End",home:"Home",left:"ArrowLeft",up:"ArrowUp",right:"ArrowRight",down:"ArrowDown",prtScn:"PrintScreen",ins:"Insert",del:"Delete",rwin:"OSRight",lwin:"OSLeft",num:"NumLock",F1:"F1",F2:"F2",F3:"F3",F4:"F4",F5:"F5",F6:"F6",F7:"F7",F8:"F8",F9:"F9",F10:"F10",F11:"F11",F12:"F12",scrollck:"ScrollLock"};
function logMessage(a){var b="chrome_rdp.js";null!=arguments.callee.caller&&null!=arguments.callee.caller.name&&""!=arguments.callee.caller.name&&(b=arguments.callee.caller.name);console.log("Function:"+b+";Message:"+a)}function logException(a){var b="chrome_rdp.js";null!=arguments.callee.caller&&null!=arguments.callee.caller.name&&""!=arguments.callee.caller.name&&(b=arguments.callee.caller.name);console.log("Function:"+b+";Exception:"+a)}
var defaultPopupTitle="RDP Alert",connection=connectionStatus.loading,connected=!1,freeTrial=!1,ChromerdpModule=null,googleOpener=null,host="",signedin=!1,signingin=!1,signingout=!1,verifyinglicense=!1,canLoginAutomaticly=!1,env={};env.width=screen.width;env.height=screen.height;env.bpp=screen.colorDepth;env.debugLevel=-1;env.fastPathSupport=!0;env.quickConnect=!1;env.password=null;env.userName=null;env.computerName="Chrome_RDP";env.adminConsole=!1;env.deviceScale=1;env.CSSScale=1;
var RDPHelper={},mruAvailable=!1,defaultTitle="Chrome RDP",fullscreenButtonNamingFunction=null,fullscreenAlert=null,settingsObj=null,mruObj=null,bookmarkObj=null,storageObjectReady=0;function $(a){try{return document.getElementById(a)}catch(b){logException(b)}}
var appWindowOrPepperDummy=function(){return chrome.app&&chrome.app.window?chrome.app.window.current():{id:null,isFullscreen:function(){return!1},isMaximized:function(){return!1},isMinimized:function(){return!1},innerBounds:{width:800,height:600,setMinimumSize:function(a,b){},setMaximumSize:function(a,b){}},outerBounds:{width:800,height:600,setMinimumSize:function(a,b){},setMaximumSize:function(a,b){}}}};
function moduleDidLoad(){try{ChromerdpModule=$(ID.rdpObject),defaultTitle=document.title,wireUI(),loadMRUs(),pageDidLoad(),setQueryStringParameters()}catch(a){logException(a)}}
function handleMessage(a){try{if(null!=a.data){var b=parseMessage(a.data);switch(b.command){case command.load:moduleDidLoad();break;case command.alert:showAlert(b.argument);break;case command.status:RDPHelper.logger.write(b.argument);break;case command.socket_connected:cancelConnectingDialog(!0);break;case command.disconnect:rdpDisconnect();break;case command.connect:var c=b.argument.split(command.delimeterArgs);rdpConnected(c[0],c[1]);break;case command.viewScale:c=b.argument.split(command.delimeterArgs);
env.deviceScale=parseFloat(c[0]);env.CSSScale=parseFloat(c[1]);break;case command.error:cancelConnectingDialog(!1);rdpError(b.argument);break;case command.ssl:sslEnabled();break;case command.clipboard_sync:syncClipboard();break;case command.clipboard_data:fetchClipboardData(b.argument);break;case command.clipboard_paste:updateClipboard(b.argument.split(command.delimeterArgs));break;case command.clipboard_formatlist_ok:endSyncClipboard();break;case command.popup:handlePopUpRequest(b.argument);break;
case command.popupClose:popupPosition(popupState.hide,!0);break;case command.standby:toggleUI(connectionStatus.standby);screenEnable();$(input.address).blur();break;case command.screenEnable:RDPHelper.ViewPort.started()||screenEnable();break;case command.activate:doGoogleAuthentication(b.argument);break;case command.licenseUpdate:doLicenseUpdate(b);break;case command.activated:doActivated();break;case command.freetrial:doFreetrial();break;case command.hasnotpaid:doHasnotpaid();break;case command.paid:doPaid();
break;case command.licenseSetURL:setLicenseURL(b.argument);break;case command.licenseOffline:$(ID.titleOffline).classList.remove(cssClass.nodisplay);break;case command.redirect:uiStrings.redirectURL=b.argument;toggleUI(connectionStatus.redirecting);sendMessage(command.redirect);break;case command.retry:sendMessage(command.retry);break;case command.certs_request:returnedCertificateHandler(b.argument);break;case command.cert_delete:returnedCertificateDeleteHandler();break;case command.authorized:doAuthorized(b);
break;case command.signin:isNumber(b.argument)||(isNumber=600),setTimeout(disableScreen,isNumber)}}}catch(d){logException(d)}}function testCrash(){sendMessage(command.doCrash)}
function handleNACLEvent(a){console.log(a.type+" "+a.lengthComputable+" "+a.loaded+" of "+a.total);switch(a.type){case "progress":1==a.lengthComputable&&a.loaded<=a.total&&($(ID.loader_row).style.display="inline",$(ID.rdpaddress_row).style.display="none",$(ID.loader_progress).style.width=a.loaded/a.total*100+"%");break;case "crash":showPopUp(-1002,"","Opps!",null,null,null)}}function isNumber(a){return null==a||"nothing"==a||""==a?!1:!isNaN(parseFloat(a))&&isFinite(a)}
function signoutLinkClick(){try{doGoogleAuthentication("https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=https://gauth.fusionlabs.net/Logout/license_logout2.aspx?si="+_instanceUUID),signingout=!0,$(ID.signingin_label).innerHTML="Signing out...",$(ID.signingin_label).style.display="inline",sendMessage(command.signout)}catch(a){logException(a)}}
function startSignIn(){try{popupPosition(popupState.hide),screenDisable(),signingout=signingin=signedin=!1,$("auth_table").style.display="table",$(ID.signin_label).style.display="none",$(ID.signin_link).style.display="none",$(ID.signingin_label).style.display="none",$(ID.email_label).innerHTML="",$(ID.email_label).style.display="none",$(ID.freeTrial_label).innerHTML="",$(ID.freeTrial_label).style.display="none",$(ID.signout_label).style.display="none",$(ID.signout_link).style.display="none"}catch(a){logException(a)}}
function signinLinkClick(){try{var a=window.navigator.userAgent,b="";-1<a.indexOf(" CrOS ",0)?(logMessage("Bypassing force login - "+a),b="https://gauth.fusionlabs.net/Logout/sign_in.aspx?si="+_instanceUUID):(logMessage("Forcing login - "+a),b="https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=https://gauth.fusionlabs.net/Logout/sign_in.aspx?si="+_instanceUUID);doGoogleAuthentication(b);signingin=!0;$(ID.signingin_label).innerHTML="Signing in...";$(ID.signingin_label).style.display=
"inline";sendMessage(command.signin)}catch(c){logException(c)}}function doGoogleAuthentication(a){try{startSignIn(),googleOpener=RDPHelper.popupManager.createPopupOpener({urlToOpen:a,onOpenHandler:doGoogleAuthentication_Open,onCloseHandler:doGoogleAuthentication_Close}),googleOpener.popup(450,500)}catch(b){logException(b)}}function doGoogleAuthentication_Open(){try{sendMessage(command.authOpened)}catch(a){logException(a)}}
function doGoogleAuthentication_Close(){try{googleOpener=null,signingout=signingin=!1,verifyinglicense=!0,$(ID.signingin_label).innerHTML="Verifying license...",_continueConnect?(_continueConnect=!1,cnctButtonClick()):sendMessage(command.authClosed)}catch(a){logException(a)}}
function doLicenseUpdate(a){var b=new XMLHttpRequest;b.open("GET",a.argument.replace("checkid_setup","checkid_immediate"),!0);b.onreadystatechange=function(){if(4==b.readyState){var a;if(200===b.status){var d,e=[],f=b.getAllResponseHeaders().split(/\r?\n/);a=0;for(d=f.length;a<d;a++)if(f[a]){var g=f[a].split(": ");e[g[0]]=g[1]}a=e["openid.mode"]}200==b.status&&a&&"id_res"==a||sendMessage(command.activate_failed)}};b.send()}
function doActivated(){freeTrial||animateShowActivateButton(!1);$(ID.black).classList.contains(cssClass.opacity50)&&$(ID.black).classList.remove(cssClass.opacity50);$(ID.black).classList.contains(cssClass.opacity0)||$(ID.black).classList.add(cssClass.opacity0);toggleUI(connectionStatus.standby);env.quickConnect&&cnctButtonClick()}
function doFreetrial(){$(ID.titlefreetrialtext).classList.remove(cssClass.nodisplay);$(ID.contents).classList.remove(cssClass.paid);$(ID.payment).classList.add(cssClass.darkgray);freeTrial=!0}function doHasnotpaid(){animateShowActivateButton(!0);$(ID.payment).classList.remove(cssClass.nodisplay);$(ID.activate_google_btn).classList.add(cssClass.nodisplay);$(ID.activate).classList.add(cssClass.marginbottom50)}
function doPaid(){freeTrial=!1;$(ID.titlefreetrialtext).classList.add(cssClass.nodisplay);$(ID.contents).classList.add(cssClass.paid);$(ID.payment).classList.remove(cssClass.darkgray)}
function doAuthorized(a){var b=a.argument.split(command.delimeterArgs);a=b[0];var c=b[1],d=b[2],b=b[3];verifyinglicense=signingout=signingin=!1;signedin="1"==a?!0:!1;"1"==b?$("auth_table").style.display="table":$("auth_table").style.display="none";$(ID.signin_label).style.display="none";$(ID.signin_link).style.display="none";$(ID.signingin_label).style.display="none";$(ID.signout_label).style.display="none";$(ID.signout_link).style.display="none";$(ID.email_label).innerHTML="";$(ID.email_label).style.display=
"none";$(ID.freeTrial_label).innerHTML="";$(ID.freeTrial_label).style.display="none";0<d.length&&($(ID.email_label).innerHTML=d+"<br />",$(ID.email_label).style.display="inline");"0"!=c||"1"==a?0<c&&($(ID.freeTrial_label).innerHTML="<a id='popup_chrome_store_link2' href='https://gauth.fusionlabs.net/license_info.aspx' target='_blank' style='cursor: pointer;'>"+c+" day(s) left in free trial</a><br />",$(ID.freeTrial_label).style.display="inline"):0<d.length&&($(ID.freeTrial_label).innerHTML="<a id='popup_chrome_store_link2' href='https://gauth.fusionlabs.net/license_info.aspx' target='_blank' style='cursor: pointer;'>Free trial has expired</a><br />",
$(ID.freeTrial_label).style.display="inline");signedin?connection==connectionStatus.redirecting||connection==connectionStatus.connecting?($(ID.signout_label).style.display="inline",$(ID.signout_link).style.display="none"):($(ID.signout_label).style.display="none",$(ID.signout_link).style.display="inline"):connection==connectionStatus.redirecting||connection==connectionStatus.connecting?($(ID.signin_label).style.display="inline",$(ID.signin_link).style.display="none"):($(ID.signin_label).style.display=
"none",$(ID.signin_link).style.display="inline")}function setPromptTextFinishDelayed(){}function popupAdvancedTab(){try{logMessage("popupAdvancedTab"),popupResponse(1)}catch(a){logException(a)}}
function handlePopUpRequest(a){try{var b=a.split(command.delimeter),c,d,e,f,g,k;c=b[0];d=b[1];e=b[2];f=b[3];g=b[4];a=0;b[5]&&0<b[5].length&&(k=b[5].split(command.delimeterArgs),2==c&&9<=k.length&&canLoginAutomaticly&&0<k[5].length&&0<k[8].length&&(a=1));2==c&&(canLoginAutomaticly=!1);2==c&&0!=a?showPopUp2(c,d,e,f,g,k,a):showPopUp(c,d,e,f,g,k)}catch(l){logException(l)}}
function parseMessage(a){try{if(null!=a){var b;try{b=a.indexOf(command.delimeter)}catch(e){b=-1}var c="",d="";-1<b?(c=a.substring(0,b),d=a.substring(b+1)):c=a;return{command:c,argument:d}}}catch(e){logException(e)}}function join(a){try{return"object"===typeof a?a.join(command.delimeterArgs):a}catch(b){logException(b)}}
function sendMessage(a,b){try{if(null!=ChromerdpModule)return blankNullorUndefined(b)&&(b=[]),args=join(b),ChromerdpModule.postMessage(a+command.delimeter+args),!0;showAlert(uiStrings.pluginError);return!1}catch(c){logException(c)}}function sendConnectMessage(){try{sendMessage(command.connect)}catch(a){logException(a)}}
function sendConnectRequest(){try{if(blankNullorUndefined($(input.address).value))_isComputeEngine?rdpError("This version of Chrome RDP is configured to run only with Google Compute Engine."):rdpError("Computer name or address is blank. Please try again.");else if(RDPHelper.ViewPort.screenDisableResizing(),screenDisable(),null!=ChromerdpModule)if(1>connection)if(invalidAddress())rdpError();else{var a=$(input.address);a.value=a.value.trim();toggleUI(connectionStatus.connecting);_isComputeEngine&&(canLoginAutomaticly=
!0);RDPHelper.ViewPort.initSizeFromSettings(function(){setScreenDepth();setLanguage();sendEnvironment();var b=100;env.quickConnect&&(b=500,env.quickConnect=!1,env.userName=null,env.password=null);intervals.connecting=setTimeout(function(){showPopUp(-1001,"","Connecting to "+a.value+"...","Cancel",null,null)},600+b);setTimeout(sendConnectMessage,b)})}else toggleUI(connectionStatus.disconnecting),sendMessage(command.disconnect);else return showAlert(uiStrings.pluginError),!1}catch(b){logException(b)}}
function invalidAddress(){try{var a=$(input.address).value,a=a.toLowerCase();if(/^127.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}|localhost|::[0-9]+$/.test(a)&&("false"==settingsObj.values.allowssh||1>a.indexOf(":")))return!0}catch(b){logException(b)}}function rdpDisconnect(){try{connection&&(connection=connectionStatus.disconnected,clearInterval(intervals.input)),toggleUI(),screenEnable(),RDPHelper.ViewPort.screenEnableResizing()}catch(a){logException(a)}}
function sendInputEventMessage(){try{sendMessage(command.sendInputEvents)}catch(a){logException(a)}}function adjustChromeRDPObjDeminsions(){try{for(var a=env.CSSScale,b=$(ID.rdpObject),c=Math.floor(env.width/a),d=Math.floor(env.height/a),e=Math.floor(1E3*a)/1E3;Math.floor(c*e)<env.width;)c++;for(;Math.floor(d*e)<env.height;)d++;b.width=c;b.height=d;$(ID.module).style.width=b.width+"px"}catch(f){logException(f)}}
function rdpConnected(a,b){try{adjustChromeRDPObjDeminsions(),intervals.input=setInterval(sendInputEventMessage,50),connected=!0,saveMRU($(input.address).value,a,b),toggleUI(connectionStatus.connected)}catch(c){logException(c)}}
function rdpError(a){try{var b=$(ID.summary);$(ID.summaryMessage).innerText=a?a:uiStrings.cnctError.format($(input.address).value);b.classList.add(cssClass.error);b.style.opacity=1;toggleUI(connectionStatus.error);screenEnable();RDPHelper.ViewPort.screenEnableResizing()}catch(c){logException(c)}}function cancelConnectingDialog(a){try{a&&_popupState==popupState.show&&popupResponse(),null!=intervals.connecting&&clearTimeout(intervals.connecting)}catch(b){logException(b)}}
function sendEnvironment(){try{env.debugLevel=settingsObj.values.debugLevel;var a=settingsObj.values.timeZone;-1==a&&(a=(new Date).getTimezoneOffset());var b=[env.width,env.height,env.bpp,env.debugLevel-1,Number(env.fastPathSupport),Number(env.quickConnect),$(input.address).value,getUserNameForAddress($(input.address).value),env.language,settingsObj.values.computername,settingsObj.values.showwallpaper,env.adminConsole.toString,getPasswordForAddress($(input.address).value),settingsObj.values.storepasswords,
settingsObj.values.allowNonNLA,settingsObj.values.useTcpNoDelay,_instanceUUID,window.navigator.userAgent,settingsObj.values.enableFontSmoothing,settingsObj.values.enableDesktopComposition,settingsObj.values.disableFullWindowDrag,settingsObj.values.disableMenuAnimations,settingsObj.values.disableTheming,settingsObj.values.disableCursorShadow,settingsObj.values.disableCursorBlinking,env.keyboard,a];sendMessage(command.environment,b)}catch(c){logException(c)}}
function setQueryStringParameters(){try{var a=document.location.search;if(a){var a=a.substring(1),b=a.split("&");for(i=0;i<b.length;i++){var c=b[i].split("="),d=c[1];switch(c[0].toLowerCase()){case "debug":isNaN(d)||(env.debugLevel=d);break;case "fastpath":if("false"==d.toLowerCase()||"0"==d)env.fastPathSupport=!1}}}setAddressFromHashtag()}catch(e){logException(e)}}
function changeButtonText(){try{connection==connectionStatus.connecting?$(input.cnctButton).innerHTML=uiStrings.cancel:connection==connectionStatus.disconnected&&($(input.cnctButton).innerHTML=uiStrings.connect)}catch(a){logException(a)}}function pageDidLoad(){try{initComputeEngine(),connection=null==ChromerdpModule||1>storageObjectReady?connectionStatus.loading:connectionStatus.standby,toggleUI();setTimeout(simplePopup_showOK.bind(this, "NOTICE: The Fusion Labs Chrome Remote Desktop app will be removed from the Chrome Web Store on January 31, 2022. Existing installations of the app will continue to function, but will no longer receive updates and security fixes. Please reference Microsoft's documentation for a list of alternative Microsoft Remote Desktop Protocol clients to ensure continued RDP access to your systems.", null), 1000);}catch(a){logException(a)}}
function pageDidUnload(){try{clearInterval(intervals.input)}catch(a){logException(a)}}
function toggleUI(a){try{"undefined"!=typeof a&&(connection=a),console.log("ToggleUI to "+connection),connection==connectionStatus.error?(standByUI(),connection=connectionStatus.standby,connected&&animateReturnToStandByUI()):connection==connectionStatus.loading?$(ID.prompt).innerHTML=uiStrings.loading:connection==connectionStatus.licenceCheck?$(ID.prompt).innerHTML=uiStrings.loading:connection==connectionStatus.standby?standByUI():connection==connectionStatus.disconnected?(standByUI(),connection=
connectionStatus.standby,connected&&animateReturnToStandByUI()):connection==connectionStatus.disconnecting?$(ID.prompt).innerHTML=uiStrings.disconnecting:connection==connectionStatus.connecting?($(ID.settings_label).style.display="inline",$(ID.settings_link).style.display="none",$(ID.license_label).style.display="inline",$(ID.license_link).style.display="none",$(ID.contactus_label).style.display="inline",$(ID.contactus_link).style.display="none",$(ID.fullscreen_label).style.display="inline",$(ID.fullscreen_link).style.display=
"none",signingin?$(ID.signingin_label).innerHTML="Signing in...":signingout?$(ID.signingin_label).innerHTML="Signing out...":verifyinglicense?$(ID.signingin_label).innerHTML="Verifying license...":signedin?($(ID.signout_label).style.display="inline",$(ID.signout_link).style.display="none"):($(ID.signin_label).style.display="inline",$(ID.signin_link).style.display="none"),$(ID.summaryMessage).innerText="",$(ID.summary).classList.remove(cssClass.error),$(ID.summary).classList.remove(cssClass.notBookmarked),
$(ID.divBookmark_link).style.display="none",$(input.address).blur(),$(input.address).disabled=!0,$(ID.contents).classList.add(cssClass.busy),$(ID.prompt).innerHTML=uiStrings.connecting,$(input.menubutton).disabled=!0,$(input.cnctButton).disabled=!0,$(input.cnctButton).classList.remove(cssClass.button),$(input.cnctButton).innerHTML=uiStrings.disconnect,$(ID.mru).className=""):connection==connectionStatus.connected?(hideObject(ID.home),$(ID.summary).classList.remove(cssClass.error),showObject(ID.session),
animateEnterStandByUI(),host=$(input.address).value,document.title=host+" - "+defaultTitle,giveFocus(ID.rdpObject),handleUIKeys(!0)):connection==connectionStatus.redirecting&&($(ID.settings_label).style.display="inline",$(ID.settings_link).style.display="none",$(ID.license_label).style.display="inline",$(ID.license_link).style.display="none",$(ID.contactus_label).style.display="inline",$(ID.contactus_link).style.display="none",$(ID.fullscreen_label).style.display="inline",$(ID.fullscreen_link).style.display=
"none",signingin?$(ID.signingin_label).innerHTML="Signing in...":signingout?$(ID.signingin_label).innerHTML="Signing out...":verifyinglicense?$(ID.signingin_label).innerHTML="Verifying license...":signedin?($(ID.signout_label).style.display="inline",$(ID.signout_link).style.display="none"):($(ID.signin_label).style.display="inline",$(ID.signin_link).style.display="none"),$(ID.summaryMessage).innerText="",$(ID.summary).classList.remove(cssClass.error),$(ID.summary).classList.remove(cssClass.notBookmarked),
$(ID.divBookmark_link).style.display="none",$(input.address).blur(),$(input.address).disabled=!0,$(ID.contents).classList.add(cssClass.busy),$(ID.prompt).innerHTML=uiStrings.redirecting.format(uiStrings.redirectURL),$(input.menubutton).disabled=!0,$(input.cnctButton).disabled=!0,$(input.cnctButton).classList.remove(cssClass.button),$(input.cnctButton).innerHTML=uiStrings.disconnect,$(ID.mru).className="")}catch(b){logException(b)}}
function screenDisable(){try{var a=$(ID.black);a.classList.remove(cssClass.opacity0_slow);a.classList.remove(cssClass.opacity0);a.classList.add(cssClass.opacity50)}catch(b){logException(b)}}
function screenEnable(){try{if(connection==connectionStatus.connected||connection==connectionStatus.standby||connection==connectionStatus.disconnected||connection==connectionStatus.disconnecting||connection==connectionStatus.error){var a=$(ID.black);a.classList.remove(cssClass.opacity0_slow);a.classList.remove(cssClass.opacity50);a.classList.add(cssClass.opacity0);setTimeout(animateReturnToStandByUIDelayedActions2,100);$(ID.contents).style.display=""}}catch(b){logException(b)}}
function animateEnterStandByUI(){try{$(ID.black).classList.remove(cssClass.opacity0),$(ID.black).classList.remove(cssClass.opacity50),$(ID.black).classList.add(cssClass.opacity100),$(ID.session).classList.add(cssClass.shown),setTimeout(animateEnterStandByUIDelayedActions1,500)}catch(a){logException(a)}}
function animateEnterStandByUIDelayedActions1(){try{$(ID.contents).style.display="none",$(ID.black).classList.add(cssClass.opacity0_slow),$(ID.black).classList.remove(cssClass.opacity100),setTimeout(animateReturnToStandByUIDelayedActions2,100),sendMessage(command.completedStandby)}catch(a){logException(a)}}
function animateReturnToStandByUIDelayedActions0(){try{$(ID.black).classList.add(cssClass.opacity100),$(ID.session).classList.remove(cssClass.shown),setTimeout(animateReturnToStandByUIDelayedActions1,500)}catch(a){logException(a)}}function animateReturnToStandByUIDelayedActions1(){try{showObject(ID.home),hideObject(ID.session),$(ID.black).classList.add(cssClass.opacity0_slow),setTimeout(screenEnable,100)}catch(a){logException(a)}}
function animateReturnToStandByUIDelayedActions2(){try{_popupState==popupState.show?screenDisable():($(ID.black).classList.remove(cssClass.opacity100),$(ID.black).classList.remove(cssClass.opacity0_slow),$(ID.black).classList.remove(cssClass.opacity50),$(ID.black).classList.remove(cssClass.opacity0))}catch(a){logException(a)}}
function animateReturnToStandByUI(){try{endAltTab();animateReturnToStandByUIDelayedActions0();var a=$(input.address).value;$(ID.summaryMessage).innerText=uiStrings.cnctEnded.format(a);$(ID.summary).style.opacity=1;$(ID.sessionMenu).classList.remove(cssClass.shown);host="";loadMRUs();connected=!1;bookmarkObj.ConnectionExists(a)||_isComputeEngine?($(ID.summary).classList.remove(cssClass.notBookmarked),$(ID.divBookmark_link).style.display="none"):($(ID.summary).classList.add(cssClass.notBookmarked),
$(ID.divBookmark_link).style.display="block")}catch(b){logException(b)}}var addBookmark_address,addBookmark_username,addBookmark_password;function addBookmark(){try{var a=$(input.address).value,b=getUserNameForAddressFromMRUs(a),c=getPasswordForAddressFromMRUs(a);addBookmark_address=a;addBookmark_username=b;addBookmark_password=c;chrome.storage.sync.get(bookmarkObj.key,addBookmarkCallback)}catch(d){logException(d)}}
function addBookmarkCallback(a){try{bookmarkObj.Populate(a);a=addBookmark_address;var b=addBookmark_username,c=addBookmark_password;addBookmark_password=addBookmark_username=addBookmark_address=null;bookmarkObj.AddConnection(a,"","",b,c);$(ID.divBookmark_link).style.display="none"}catch(d){logException(d)}}
function bookmarkHelperCallback(){try{var a=$(input.address).value;$(ID.summary).classList.remove(cssClass.notBookmarked);$(ID.divBookmark_link).style.display="none";0<a.length&&!_isComputeEngine&&($(ID.summaryMessage).innerText==uiStrings.cnctEnded.format(a)&&!bookmarkObj.ConnectionExists(a)||invalidAddress(a))&&($(ID.summary).classList.add(cssClass.notBookmarked),$(ID.divBookmark_link).style.display="block")}catch(b){logException(b)}}
function focusOnAddressBar(){try{env.quickConnect||giveFocus(input.address)}catch(a){logException(a)}}
function standByUI(){try{$(ID.rdpaddress_row).style.display="inline",$(ID.loader_row).style.display="none",$(ID.settings_label).style.display="none",$(ID.settings_link).style.display="inline",$(ID.license_label).style.display="none",$(ID.license_link).style.display="inline",$(ID.contactus_label).style.display="none",$(ID.contactus_link).style.display="inline",$(ID.fullscreen_label).style.display="none",$(ID.fullscreen_link).style.display="inline",signingin?$(ID.signingin_label).innerHTML="Signing in...":
signingout?$(ID.signingin_label).innerHTML="Signing out...":verifyinglicense?$(ID.signingin_label).innerHTML="Verifying license...":signedin?($(ID.signout_label).style.display="none",$(ID.signout_link).style.display="inline"):($(ID.signin_label).style.display="none",$(ID.signin_link).style.display="inline"),$(ID.contents).classList.remove(cssClass.busy),_isComputeEngine||($(input.address).disabled=!1,$(input.menubutton).disabled=!1,$(input.menubutton).classList.add(cssClass.button)),$(input.cnctButton).disabled=
!1,$(input.cnctButton).classList.add(cssClass.button),$(input.cnctButton).innerHTML=uiStrings.connect,$(ID.prompt).innerHTML=uiStrings.entryPrompt,handleUIKeys(!1),document.title=defaultTitle,setTimeout(focusOnAddressBar,500)}catch(a){logException(a)}}function giveFocus(a){try{var b=$(a);b.tabIndex=0;b.focus()}catch(c){logException(c)}}
function loadMRUs(){try{var a=mruObj.getMRUList(),b=$(ID.mru);b.innerHTML="";mruAvailable=0<a.length;var c=5;c>a.length&&(c=a.length);for(i=0;i<c;i++){var d=document.createElement("div");d.classList.add(cssClass.mruitem);d.innerText=a[i];d.addEventListener("click",mruListItemClick);b.appendChild(d)}}catch(e){logException(e)}}function saveMRU(a,b,c){try{0<a.length&&mruObj.addMRU(a,b,c)}catch(d){logException(d)}}
function popup_ComputeEngine_Enabled(){try{simplePopup_showOK("You are currently connected using Google Compute Engine. To connect to a different RDP server, please close the current window and launch the appropriate Compute Engine instance or start Chrome RDP from the Chrome launcher.",popup_DisabledResize_ok)}catch(a){logException(a)}}
function toggleMRU(){try{if(!$(input.menubutton).disabled)if(_isComputeEngine)popup_ComputeEngine_Enabled();else if(mruAvailable){var a=$(ID.mru);if(!a.classList.contains(cssClass.shown)){var b=0,c=function(d){b++;2===b&&(this.removeEventListener("click",c),a.classList.remove(cssClass.shown))};document.addEventListener("click",c);a.classList.add(cssClass.shown)}}}catch(d){logException(d)}}
function mruListItemClick(a){try{var b=a.target;$(input.address).value=b.innerText;toggleMRU();focusOnAddressBar()}catch(c){logException(c)}}function getUserNameForAddress(a){try{var b="";_isComputeEngine?b=_computeEngineUserName:env.quickConnect&&(b=env.userName);if(!blankNullorUndefined(b))return b;b=getUserNameForAddressFromBookmarks(a);if(!blankNullorUndefined(b))return b;b=getUserNameForAddressFromMRUs(a);return blankNullorUndefined(b)?"":b}catch(c){logException(c)}}
function getUserNameForAddressFromMRUs(a){try{var b=mruObj.getUserNameFromAddress(a);return blankNullorUndefined(b)?"":b}catch(c){logException(c)}}function getUserNameForAddressFromBookmarks(a){try{var b=bookmarkObj.getUserNameFromAddress(a);return blankNullorUndefined(b)?"":b}catch(c){logException(c)}}
function getPasswordForAddress(a){try{var b="";_isComputeEngine?b=_computeEnginePassword:env.quickConnect&&(b=env.password);if(!blankNullorUndefined(b))return b=RDPHelper.codec.convertUTF162UTF8(b),b=RDPHelper.codec.base64encodeUTF8(b);b=getPasswordForAddressFromBookmarks(a);if(!blankNullorUndefined(b))return b;b=getPasswordForAddressFromMRUs(a);return blankNullorUndefined(b)?"":b}catch(c){logException(c)}}
function getPasswordForAddressFromMRUs(a){try{var b=mruObj.getPasswordFromAddress(a);return blankNullorUndefined(b)?"":b}catch(c){logException(c)}}function getPasswordForAddressFromBookmarks(a){try{var b=bookmarkObj.getPasswordFromAddress(a);return blankNullorUndefined(b)?"":b}catch(c){logException(c)}}function showObject(a){try{$(a).style.visibility="visible"}catch(b){logException(b)}}function hideObject(a){try{$(a).style.visibility="hidden"}catch(b){logException(b)}}
function toggleShown(a){try{$(a).classList.toggle(cssClass.shown)}catch(b){logException(b)}}function setScreenDepth(){try{var a=settingsObj.values.screendepth;blankNullorUndefined(a)&&(settingsObj.values.screendepth="32",settingsObj.save(),a=32);env.bpp=a}catch(b){logException(b)}}function setLanguage(){try{var a=settingsObj.values.language;blankNullorUndefined(a)&&(settingsObj.values.language="0x00000409",settingsObj.save(),a=1033);env.language=a}catch(b){logException(b)}}
function sslEnabled(){}function handleUIKeys(a){try{a?(document.onkeydown=onKeyHandler,document.onkeyup=onKeyHandler):(document.onkeydown=onKeyHandler2,document.onkeyup=null)}catch(b){logException(b)}}function cleanSystemKey(){try{intervals.systemKey=null}catch(a){logException(a)}}
function onKeyHandler(){try{switch(event.keyCode){case 82:event.ctrlKey&&blockKey(event);break;case keyCodes.rwin:case keyCodes.lwin:intervals.systemKey||(intervals.systemKey=setInterval(cleanSystemKey,6E4));break;case keyCodes.esc:blockKey(event);endAltTab();break;case keyCodes.F1:case keyCodes.F2:case keyCodes.F3:case keyCodes.F4:case keyCodes.F5:case keyCodes.F6:case keyCodes.F7:case keyCodes.F8:case keyCodes.F9:case keyCodes.F10:case keyCodes.F11:case keyCodes.F12:blockKey(event);endAltTab();
break;case keyCodes.tab:case keyCodes.up:case keyCodes.down:case keyCodes.left:case keyCodes.right:resetAltTabTimer();break;default:endAltTab()}}catch(a){logException(a)}}function onKeyHandler2(){try{switch(event.keyCode){case keyCodes.F11:RDPHelper.ViewPort.toggleFullscreen(popup_DisabledResize);event.preventDefault();break;case keyCodes.esc:RDPHelper.ViewPort.isFullscreen()&&RDPHelper.ViewPort.toggleFullscreen(popup_DisabledResize),event.preventDefault()}}catch(a){logException(a)}}
function blockKey(a){try{sendKeyFromUI(a),a.returnValue=!1,a.keyCode=0}catch(b){logException(b)}}function sendKeyFromUI(a){try{var b=a.keyCode,c=0;"keydown"==a.type&&(c=1);sendMessage(command.systemKey,[b,c]);$(ID.rdpObject).focus()}catch(d){logException(d)}}function sendCtrlAltDel(){try{sendKeyCombo("!C!A!D")}catch(a){logException(a)}}function sendStartMenu(){try{sendKeyCombo("!C!E")}catch(a){logException(a)}}function sendPrintScreen(){try{sendKeyCombo("!P")}catch(a){logException(a)}}
function sendAltPrintScreen(){try{sendKeyCombo("!A!P")}catch(a){logException(a)}}
function sendKeyCombo(a){try{endAltTab();var b=[];for(i=0;i<a.length;i++){var c=a.charAt(i).toUpperCase();if("!"==c)switch(c=a.charAt(++i).toUpperCase(),c){case "A":b.push(keyCodes.alt);break;case "C":b.push(keyCodes.ctrl);break;case "D":b.push(keyCodes.del);break;case "E":b.push(keyCodes.esc);break;case "H":b.push(keyCodes.home);break;case "I":b.push(keyCodes.ins);break;case "N":b.push(keyCodes.end);break;case "P":b.push(keyCodes.prtScn);break;case "S":b.push(keyCodes.shift);break;case "T":b.push(keyCodes.tab);
break;case "U":b.push(keyCodes.pgup);break;case "V":b.push(keyCodes.pgdwn);break;case "W":b.push(keyCodes.win)}else{var d=c.charCodeAt(0);b.push(d)}}sendMessage(command.comboKey,b);$(ID.rdpObject).focus()}catch(e){logException(e)}}var altTabbing=!1,altTabTimeout=null,should=!1;
function altTab(){try{altTabbing?(resetAltTabTimer(),sendMessage(command.systemKey,[keyCodes.tab,1]),sendMessage(command.systemKey,[keyCodes.tab,0])):(document.onClick=endAltTab,$(ID.rdpObject).onmousedown=endAltTab,sendMessage(command.systemKey,[keyCodes.alt,1]),sendMessage(command.systemKey,[keyCodes.tab,1]),sendMessage(command.systemKey,[keyCodes.tab,0]),$(ID.rdpObject).focus(),altTabbing=!0,should=!1),resetAltTabTimer()}catch(a){logException(a)}}
function resetAltTabTimer(){try{should=!1,clearInterval(intervals.altTab),intervals.altTab=setInterval(endAltTab,1E3)}catch(a){logException(a)}}function endAltTab(){try{should?altTabbing&&(altTabbing=!1,sendMessage(command.systemKey,[keyCodes.alt,0]),sendMessage(command.comboKey,[keyCodes.alt]),document.onClick=null,$(ID.rdpObject).onmousedown=null,clearInterval(intervals.altTab)):should=!0}catch(a){logException(a)}}
function beforeunloadhandler(){if(connected)return"Your Remote session will be disconnected.  You can reconnect to this session later and your programs on the remote computer will continue to run."}function setAddressFromHashtag(){try{var a=document.location.hash;a&&1<a.length&&($(input.address).value=a.substr(1).replace("%3A",":"),env.quickConnect=!0,document.location.hash="")}catch(b){logException(b)}}
function hashchangehandler(){try{1<document.location.hash.length&&(connected?location.reload():(setAddressFromHashtag(),cnctButtonClick()))}catch(a){logException(a)}}var _instanceUUID="";function generateUUID(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var c=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==b?c:c&7|8).toString(16)})}var _isComputeEngine=!1,_computeEngineUserName="",_computeEnginePassword="";
chrome&&chrome.runtime&&chrome.runtime.onMessage&&chrome.runtime.onMessage.addListener(function(a,b,c){try{logMessage("message="+a);if("undefined"==a||null==a||"undefined"==a.messageType||null==a.messageType)throw"unrecognized message";if("connect"==a.messageType&&connection==connectionStatus.standby){var d=appWindowOrPepperDummy();d.env.urlAddress=a.urlAddress;d.env.userName=a.userName;d.env.password=a.password;d.env.isComputeEngine=a.isComputeEngine;initComputeEngine();0<a.urlAddress.length&&0<
a.userName.length&&cnctButtonClick()}}catch(e){logException(e)}});
function initComputeEngine(){try{if(chrome.app&&chrome.app.window){var a=appWindowOrPepperDummy();a.env&&(0<a.env.urlAddress.length&&(env.quickConnect=!0,$(input.address).value=a.env.urlAddress,env.userName=a.env.userName,env.password=a.env.password),a.env.isComputeEngine&&(_isComputeEngine=!0,_computeEngineUserName=a.env.userName,_computeEnginePassword=a.env.password,console.log("Waiting for Compute Engine")));_isComputeEngine&&($(input.address).disabled=!0,$(input.menubutton).style.display="none",
canLoginAutomaticly=!0,$("tdButton").style.paddingLeft="7px",$("bookmarksHeader").style.display="none",$("bookmarks").style.display="none")}}catch(b){logException(b)}}
function initForm(){try{var a=function(){},b=new CustomEvent("RDPInit",{detail:a,bubbles:!0,cancelable:!0});document.dispatchEvent(b);RDPHelper=new a;black.classList.contains(cssClass.opacity0)&&black.classList.remove(cssClass.opacity0);black.classList.contains(cssClass.opacity50)||black.classList.add(cssClass.opacity50);if(!UIprocessed){for(var c=$(ID.userControls),d=[["Minimize","Minimize",RDPHelper.ViewPort.minimizeScreen,[cssClass.button]],["Disconnect","Disconnect",sendConnectRequest,[cssClass.button]],
["Ctrl+Alt+Del","Ctrl+Alt+Del",sendCtrlAltDel,[cssClass.button]],["Switch_Task","Switch Task",altTab,[cssClass.button]],["Start_Menu","Start Menu",sendStartMenu,[cssClass.button]],["Print_Screen","Print Screen",sendPrintScreen,[cssClass.button]],["Alt+Print_Screen","Alt+Print Screen",sendAltPrintScreen,[cssClass.button]]],a=0;a<d.length;a++){var e=document.createElement("button");e.setAttribute("id",d[a][0]);e.innerText=d[a][1].replace("_"," ");e.addEventListener("click",d[a][2]);for(b=0;b<d[a][3].length;b++)e.classList.add(d[a][3][b]);
c.appendChild(e);if("undefined"!==typeof d[a][4])d[a][4]()}var f=$(ID.module),g=f.getAttribute("type");f.addEventListener("message",handleMessage,!0);f.addEventListener("loadstart",handleNACLEvent,!0);f.addEventListener("progress",handleNACLEvent,!0);f.addEventListener("error",handleNACLEvent,!0);f.addEventListener("about",handleNACLEvent,!0);f.addEventListener("crash",handleNACLEvent,!0);f.addEventListener("load",handleNACLEvent,!0);f.addEventListener("loadend",handleNACLEvent,!0);var k=document.createElement("embed");
k.setAttribute("name","nacl_module");k.setAttribute("id","chrome_rdp");k.setAttribute("width",800);k.setAttribute("height",600);k.setAttribute("src","chromerdp.nmf");k.setAttribute("type",g);f.appendChild(k);UIprocessed=!0}window.addEventListener("hashchange",hashchangehandler);if(null==_instanceUUID||""==_instanceUUID)_instanceUUID=generateUUID();pageDidLoad()}catch(l){logException(l)}}function addressKeyDown(a){try{a&&13==a.keyCode&&cnctButtonClick()}catch(b){logException(b)}}
function popupKeyDown(a){try{a&&13==a.keyCode&&popupYesClick()}catch(b){logException(b)}}function addressChange(){}var _continueConnect=!1;function cnctButtonClick(){try{var a=!1;_isComputeEngine&&(a=!1);!a||signedin||signingin||verifyinglicense?(_continueConnect=!1,sendConnectRequest()):(_continueConnect=!0,signinLinkClick())}catch(b){logException(b)}}function sessionTabClick(){try{toggleShown(ID.sessionMenu)}catch(a){logException(a)}}
function popupYesClick(){try{tabViewDisabled||popupResponse(1)}catch(a){logException(a)}}function popupNoClick(){try{tabViewDisabled||popupResponse()}catch(a){logException(a)}}function blackWebkitAnimationEnd(){try{$(ID.black).classList.remove(cssClass.opacity0);var a=$(ID.black);a.classList.contains(cssClass.opacity0)&&a.classList.add(cssClass.opacity50);a.classList.contains(cssClass.homeInFromLeft)&&a.classList.add(cssClass.homeInFromLeftFinal)}catch(b){logException(b)}}
function activateWebkitAnimationEnd(){try{var a=$(ID.activate);a.classList.contains(cssClass.homeInFromTop)&&a.classList.add(cssClass.homeInFromTopFinal);a.classList.contains(cssClass.homeOutToTop)&&(a.classList.add(cssClass.homeOutToTopFinal),$(input.address).focus())}catch(b){logException(b)}}
function activateGoogleWebkitAnimationEnd(){try{var a=$(ID.activate_google);a.classList.contains(cssClass.homeOutToRight)&&a.classList.add(cssClass.homeOutToRightFinal);a.classList.contains(cssClass.homeInFromLeft)&&a.classList.add(cssClass.homeInFromLeftFinal)}catch(b){logException(b)}}
function activateUsernameWebkitAnimationEnd(){try{var a=$(ID.activate_username);a.classList.contains(cssClass.homeOutToRight)&&a.classList.add(cssClass.homeOutToRightFinal);a.classList.contains(cssClass.homeInFromLeft)&&a.classList.add(cssClass.homeInFromLeftFinal)}catch(b){logException(b)}}function activateGoogleNextClick(){try{animateActivateOption($(ID.activate_google),$(ID.activate_username))}catch(a){logException(a)}}
function activateUserNameNextClick(){try{animateActivateOption($(ID.activate_username),$(ID.activate_google))}catch(a){logException(a)}}function settingsLinkClick(){try{return showPopUp(-1,"","Chrome RDP "+$(ID.settings_link).innerHTML,"OK","Cancel",null),!1}catch(a){logException(a)}}function contactusLinkClick(){try{return showPopUp(-1E3,"","Chrome RDP "+$(ID.contactus_link).innerHTML,"OK",null,null),!1}catch(a){logException(a)}}
function fullscreenLinkClick(){try{return RDPHelper.ViewPort.toggleFullscreen(popup_DisabledResize),!1}catch(a){logException(a)}}function doClearDataCache(){try{showPopUp(-2,"","Are you sure you want to clear saved Remote Identities?","OK","Cancel",null)}catch(a){logException(a)}}function syncClipboard(a){try{RDPHelper.clipboard.scheduleNextFormatListTimeout(function(){sendMessage(command.clipboard_sync,RDPHelper.clipboard.getTypes())})}catch(b){logException(b)}}
function endSyncClipboard(){try{RDPHelper.clipboard.cancelNextFormatListTimeout()}catch(a){logException(a)}}function fetchClipboardData(a){try{sendMessage(command.clipboard_data,[RDPHelper.clipboard.getData(a)]),setTimeout(syncClipboard,100)}catch(b){logException(b)}}function updateClipboard(a){try{var b=[];if(0==a.length%2)for(var c=0;c<a.length;c+=2)b.push({type:a[c],value:a[c+1]});RDPHelper.clipboard.decodeItems(b);RDPHelper.clipboard.setItems(b)}catch(d){logException(d)}}
function pasteTester(a){}
function wireUI(){try{loadStorageObjects();var a=$(input.address);a.addEventListener("keydown",addressKeyDown);a.addEventListener("change",addressChange);a.addEventListener("paste",pasteTester);$(ID.menubutton).addEventListener("click",toggleMRU);$(input.cnctButton).addEventListener("click",cnctButtonClick);$(input.sessionTab).addEventListener("click",sessionTabClick);$(popupIDs.popup_auth_link).addEventListener("click",doGoogleAuthentication);$(popupIDs.btnYes).addEventListener("click",popupYesClick);
$(popupIDs.btnNo).addEventListener("click",popupNoClick);$(input.payment_checkout).addEventListener("click",doLicenseAuthentication);$(ID.black).addEventListener("webkitTransitionEnd",blackWebkitAnimationEnd);$(ID.activate).addEventListener("webkitAnimationEnd",activateWebkitAnimationEnd);$(ID.activate_google).addEventListener("webkitAnimationEnd",activateGoogleWebkitAnimationEnd);$(ID.activate_username).addEventListener("webkitAnimationEnd",activateUsernameWebkitAnimationEnd);$(ID.activate_google_btn).addEventListener("click",
doGoogleAuthentication);$(ID.activate_google_next).addEventListener("click",activateGoogleNextClick);$(ID.activate_username_next).addEventListener("click",activateUserNameNextClick);$(ID.settings_link).addEventListener("click",settingsLinkClick);$(ID.contactus_link).addEventListener("click",contactusLinkClick);$(ID.fullscreen_link).addEventListener("click",fullscreenLinkClick);$(ID.signout_link).addEventListener("click",signoutLinkClick);$(ID.signin_link).addEventListener("click",signinLinkClick);
$(ID.addBookmark_link).addEventListener("click",addBookmark);$(input.ScreenSize).addEventListener("change",screenSizeDropdownValueChanged);$(input.CertificateDelete).addEventListener("click",certificateDeleteButtonClickHandler);$(input.ClearSSLCache).addEventListener("click",certificateDeleteAllButtonClickHandler);$(input.StorePasswords).addEventListener("change",storePasswordsClickHandler);document.addEventListener("onClipboardUpdate",syncClipboard);var b=$(ID.menutab);b.onmousedown=sessionTabMouseDown;
b.onmouseup=sessionTabMouseUp;$(input.sessionTab).ondragstart=function(a){a.preventDefault()};var c=$(ID.userControls);c.onmousemove=sessionUserControlsMouseMove;c.onmouseout=sessionUserControlsMouseOut;var d=$(ID.session);d.onmouseup=sessionMouseUp;d.onmousemove=sessionMouseMove;initializeTabView(ID.settings);simplePopup_init()}catch(e){logException(e)}}
function loadStorageObjects(){try{if(settingsObj=new RDPHelper.SettingsObject(function(){RDPHelper.ViewPort.loadSettings(loadSettingsFinalize)}),mruObj=new RDPHelper.MRUObject(loadMRUs),bookmarkObj=new RDPHelper.BookmarkObject($(ID.bookmarks),connectBookmark,deleteBookmark,connectBookmarkNewWindow),chrome.storage){try{--storageObjectReady,chrome.storage.local.get(settingsObj.key,SettingsObjectLoadedCallback)}catch(a){logException(a)}try{--storageObjectReady,chrome.storage.local.get(mruObj.key,MRUObjectLoadedCallback)}catch(a){logException(a)}try{--storageObjectReady,
chrome.storage.sync.get(bookmarkObj.key,BookmarkObjectLoadedCallback)}catch(a){logException(a)}}else loadSettingsFinalize(),storageObjectLoaded(),bookmarkObj.Refresh}catch(a){logException(a)}}function SettingsObjectLoadedCallback(a){try{settingsObj.Populate(a),storageObjectReady+=1,0==storageObjectReady&&storageObjectLoaded()}catch(b){logException(b)}}
function MRUObjectLoadedCallback(a){try{mruObj.Populate(a),storageObjectReady+=1,0==storageObjectReady&&storageObjectLoaded()}catch(b){logException(b)}}function BookmarkObjectLoadedCallback(a){try{bookmarkObj.Populate(a),storageObjectReady+=1,0==storageObjectReady&&storageObjectLoaded()}catch(b){logException(b)}}function storageObjectLoaded(){try{setScreenDepth(),setLanguage(),storageObjectReady+=1,pageDidLoad()}catch(a){logException(a)}}
function loadSettingsFinalize(){try{env.quickConnect?env.quickConnect&&cnctButtonClick():(sendEnvironment(),black.classList.remove(cssClass.opacity50),black.classList.add(cssClass.opacity0))}catch(a){logException(a)}}var popup_DisabledResize_IsOpen=!1;
function popup_DisabledResize(){try{popup_DisabledResize_IsOpen||(popup_DisabledResize_IsOpen=!0,screenDisable(),simplePopup_showOK("To maximize or toggle the fullscreen, please disconnect your current session first.",popup_DisabledResize_ok))}catch(a){logException(a)}}function popup_DisabledResize_ok(){try{screenEnable(),popup_DisabledResize_IsOpen=!1}catch(a){logException(a)}}var DeleteBookmarkID=null,DeleteBookmarkName=null;
function deleteBookmark(a){try{DeleteBookmarkID=a.target.parentNode.parentNode.parentNode.attributes.bookmarkid.value,DeleteBookmarkName=a.target.parentNode.parentNode.parentNode.attributes.bookmarkName.value,screenDisable(),simplePopup_showOKCancel("Are you sure you want to delete the connection to '"+DeleteBookmarkName+"'?",deleteBookmark_ok,deleteBookmark_cancel)}catch(b){logException(b)}}
function deleteBookmark_ok(){try{bookmarkObj.DeleteConnection(DeleteBookmarkID),screenEnable()}catch(a){logException(a)}}function deleteBookmark_cancel(){try{screenEnable()}catch(a){logException(a)}}function connectBookmark(a){try{var b=a.target.attributes.href.value;_isComputeEngine&&b!=$(input.address).value?popup_ComputeEngine_Enabled():($(input.address).value=b,cnctButtonClick(),a.preventDefault())}catch(c){logException(c)}}
function connectBookmarkNewWindow(a){try{var b=getHREFTargetValue(a);if(b){var c="nacl.html#"+b.replace(":","%3A");if("undefined"!==typeof chrome.app.window){var d=appWindowOrPepperDummy(),e=d.outerBounds.left+50,f=d.outerBounds.top+50,g=d.innerBounds.width,k=d.innerBounds.height,b="normal";RDPHelper.ViewPort.isFullscreen()?b="fullscreen":d.isMaximized()&&(b="maximized");chrome.app.window.create(c,{left:e,top:f,width:g,height:k,state:b},function(a){})}else window.open(c,"_blank")}a.preventDefault()}catch(l){logException(l)}}
function getHREFTargetValue(a){try{var b=!1;"undefined"!==typeof a.target.parentNode.attributes.href?b=a.target.parentNode.attributes.href.value:"undefined"!==typeof a.target.attributes.href&&(b=a.target.attributes.href.value);return b}catch(c){logException(c)}}function initializeTabView(a){try{var b=$(a).children[ID.settingsTabs].children;for(a=0;a<b.length;a++)b[a].addEventListener("click",tabClicked,!1)}catch(c){logException(c)}}var tabViewDisabled=!1;
function tabClicked(a){try{if(!tabViewDisabled){for(var b=a.currentTarget,c=0;null!=(b=b.previousElementSibling);)c++;setTab(a.currentTarget.parentNode.parentNode.id,c)}}catch(d){logException(d)}}function setTab(a,b){try{for(var c=$(a),d=c.children[ID.settingsTabs].children,e=0;e<d.length;e++)d[e].className=e==b?"active":"";for(var f=c.children[ID.settingsPages].children,e=0;e<f.length;e++)f[e].style.display=e==b?"":"none";popupReposition(!1)}catch(g){logException(g)}}var titlePrefix="Chrome RDP - ";
function backupBookmarks(){try{chrome.bookmarks.search(titlePrefix,saveRDPBookmarks)}catch(a){logException(a)}}function saveRDPBookmarks(a){try{var b=[];for(i=0;i<a.length;i++){var c=a[i].url,d=c.indexOf("#");if(0<d){var e=c.slice(d+1).trim();if(!blankNullorUndefined(e)){var f=a[i].title.slice(titlePrefix.length).trim();blankNullorUndefined(f)&&(f=e);var g={title:null,address:null};g.title=f;g.address=e;b.push(g)}}}0<b.length&&bookmarkObj.MassAddConnections(b)}catch(k){logException(k)}}
var _sessionTabIsMouseDown=0;function sessionTabMouseUp(){try{sessionUserControlsStopWatch();var a=$(ID.menutab);a.onmousemove=null;a.onmouseout=null;_sessionTabIsMouseDown=0;sessionUserControlsStartWatch()}catch(b){logException(b)}}function sessionTabMouseDown(a){try{sessionUserControlsStopWatch();var b=$(ID.menutab);b.onmousemove=sessionTabMouseMove;b.onmouseout=sessionTabMouseOut;_sessionTabIsMouseDown=1}catch(c){logException(c)}}
function sessionTabMouseMove(a){try{sessionUserControlsStopWatch();_sessionTabIsMouseDown=1;var b=$(ID.menutab),c=a.clientX,d=b.offsetWidth;0!=d%2&&--d;a=d/2;var e=$(ID.userControls),f=e.offsetWidth-a,g=c-e.offsetLeft-a;g+a>f-3?g=f-a-4:3>g&&(g=3);b.style.marginLeft=g+"px"}catch(k){logException(k)}}function sessionTabMouseOut(){}var _sessionUserControlsInterval=null;
function sessionUserControlsWaitForClose(){try{sessionUserControlsStopWatch(),$(ID.sessionMenu).classList.contains(cssClass.shown)&&toggleShown(ID.sessionMenu)}catch(a){logException(a)}}function sessionUserControlsStopWatch(){try{null!==_sessionUserControlsInterval&&(clearInterval(_sessionUserControlsInterval),_sessionUserControlsInterval=null)}catch(a){logException(a)}}
function sessionUserControlsStartWatch(){try{sessionUserControlsStopWatch(),_sessionUserControlsInterval=setInterval(sessionUserControlsWaitForClose,1E3)}catch(a){logException(a)}}function sessionUserControlsMouseMove(a){try{sessionUserControlsStopWatch()}catch(b){logException(b)}}function sessionUserControlsMouseOut(a){try{sessionUserControlsStartWatch()}catch(b){logException(b)}}function sessionMouseUp(a){try{1==_sessionTabIsMouseDown&&sessionTabMouseUp(a)}catch(b){logException(b)}}
function sessionMouseMove(a){try{1==_sessionTabIsMouseDown&&sessionTabMouseMove(a)}catch(b){logException(b)}}function documentContextMenuPreventDefault(a){try{a.preventDefault()}catch(b){logException(b)}}try{document.addEventListener("DOMContentLoaded",initForm,!1),document.addEventListener("DOMContentUnloaded",pageDidUnload,!1)}catch(a){logException(a)}window.testCrash=testCrash;
(function(){function a(){var a=[],c=0,d=null,e=function(){try{var c=!1,d=null;g&&(d=g.GetClipboardTypes());null==d&&(d=[]);-1<d.indexOf("rdp/flag")&&(a=d);if(d.length!=a.length)c=!0;else for(var e=0;e<d.length;e++)if(d[e]!=a[e]){c=!0;break}if(c){var f=new CustomEvent("onClipboardUpdate",{detail:{oldValue:a,newValue:d},bubbles:!0,cancelable:!0});a=d;document.dispatchEvent(f)}}catch(k){console.log(k)}},f=function(a){try{a=""+a;for(var b="",c=a.length;10>c;c++)b+="0";return b+a}catch(d){console.log(d)}},
g=null,k=function(a){try{g=a,g.AttachClipboardHelper(e)}catch(b){console.log(b)}};try{chrome.runtime&&chrome.runtime.getBackgroundPage&&chrome.runtime.getBackgroundPage(k)}catch(l){console.log(l)}return{scheduleNextFormatListTimeout:function(a){c+=1;4<c?c=0:d=setTimeout(a,60^c)},cancelNextFormatListTimeout:function(){clearTimeout(d);c=0},getTypes:function(c){return g?a:["text/plain","text/html"]},setItems:function(a){try{g&&(a.push({type:"rdp/flag",value:"rdp/flag"}),g.AddItems(a))}catch(b){console.log(b)}},
getData:function(a){try{if(g){var b=g.GetData(a);if("text/html"==a){a=20;var c=b.indexOf("\x3c!--StartFragment--\x3e");-1==c&&(a=21,c=b.indexOf("\x3c!--StartFragment --\x3e"));-1!=c&&(c+=a);var d=b.lastIndexOf("\x3c!--EndFragment--\x3e");-1==d&&(d=b.lastIndexOf("\x3c!--EndFragment --\x3e"));if(-1==d||-1==c)b="<html><body>\x3c!--StartFragment--\x3e"+b+"\x3c!--EndFragment--\x3e</body></html>",c=b.indexOf("\x3c!--StartFragment--\x3e")+20,d=b.lastIndexOf("\x3c!--EndFragment--\x3e");b="Version:0.9\r\nStartHTML:0000000105\r\nEndHTML:"+
f(105+b.length)+"\r\nStartFragment:"+f(105+c)+"\r\nEndFragment:"+f(105+d)+"\r\n"+b;b=RDPHelper.codec.convertUTF162UTF8(b);b=RDPHelper.codec.base64encodeUTF8(b)}else b=RDPHelper.codec.base64encodeUTF16(b);return b}return"TESTTEXT \u30b4"}catch(e){console.log(e)}},decodeItems:function(a){try{for(var b=0;b<a.length;b++){var c=a[b];if("text/plain"==c.type){var d=RDPHelper.codec.base64decode2UTF16(c.value);c.value=RDPHelper.codec.base64decode2UTF16(c.value);0==d.charCodeAt(d.length-1)?c.value=d.substr(0,
d.length-1):c.value=d}else if("text/html"==c.type){c.value=RDPHelper.codec.base64decode2UTF8(c.value);var e=c.value.indexOf("StartHTML:"),f=c.value.indexOf("EndHTML:"),g=c.value.indexOf("StartFragment:");if(-1<e&&-1<f&&-1<g){var k=parseInt(c.value.substring(e+10,f)),m=parseInt(c.value.substring(f+8,g));k&&m&&k<m&&c.value.length>=m&&(c.value=c.value.substring(k,m))}c.value=RDPHelper.codec.convertUTF82UTF16(c.value)}else c.value=RDPHelper.codec.base64decode2AB(c.value)}}catch(h){console.log(h)}}}}document.addEventListener("RDPInit",
function(b){try{b.detail.prototype.clipboard=a()}catch(c){console.log(c)}})})();
(function(){function a(){return{base64encodeAB:function(a){try{var c=new Uint8Array(a);a="";for(var d=0;d<c.byteLength;d++)a+=String.fromCharCode(c[d]);return window.btoa(a)}catch(e){console.log(e)}},base64encodeUTF8:function(a){try{for(var c=new ArrayBuffer(a.length),d=new Uint8Array(c),e=0,f=a.length;e<f;e++)d[e]=a.charCodeAt(e);return this.base64encodeAB(c)}catch(g){console.log(g)}},base64encodeUTF16:function(a){try{for(var c=new ArrayBuffer(2*a.length),d=new Uint16Array(c),e=0,f=a.length;e<f;e++)d[e]=
a.charCodeAt(e);return this.base64encodeAB(c)}catch(g){console.log(g)}},base64decode2AB:function(a,c){try{var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(a.length-1)),e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(a.length-2)),f=Math.floor(a.length/4*3);64==d&&f--;64==e&&f--;c&&0!=f%2&&(f+=1);var g=new ArrayBuffer(f),k,l,p,n,u,r,q,x,e=d=0;k=new Uint8Array(g);a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");for(d=0;d<f;d+=3)u=
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(e++)),r="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(e++)),q="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(e++)),x="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(e++)),l=u<<2|r>>4,p=(r&15)<<4|q>>2,n=(q&3)<<6|x,k[d]=l,64!=q&&(k[d+1]=p),64!=x&&(k[d+2]=n);return g}catch(t){console.log(t)}},base64decode2UTF16:function(a){try{var c=
new Uint16Array(this.base64decode2AB(a,!0));a="";for(var d=0;d<c.length;d++)a+=String.fromCharCode(c[d]);return a}catch(e){console.log(e)}},base64decode2UTF8:function(a){try{var c=new Uint8Array(this.base64decode2AB(a,!0));a="";for(var d=0;d<c.length;d++)a+=String.fromCharCode(c[d]);return a}catch(e){console.log(e)}},convertUTF162UTF8:function(a){try{return unescape(encodeURIComponent(a))}catch(c){console.log(c)}},convertUTF82UTF16:function(a){try{return decodeURIComponent(escape(a))}catch(c){console.log(c)}}}}
document.addEventListener("RDPInit",function(b){try{b.detail.prototype.codec=a()}catch(c){console.log(c)}})})();function customStringProtoTypeFormat(){try{var a=arguments;return this.replace(/{(\d+)}/g,function(b,c){return"undefined"!=typeof a[c]?a[c]:b})}catch(b){console.log(b)}}String.prototype.format=customStringProtoTypeFormat;function customStringProtoTypeTrim(){try{return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}catch(a){console.log(a)}}String.prototype.trim=String.prototype.trim||customStringProtoTypeTrim;
function customObjectProtoTypeWatch(a,b){try{var c=this[a],d=c,e=function(){return d},f=function(e){c=d;return d=b.call(this,a,c,e)};delete this[a]&&Object.defineProperty(this,a,{get:e,set:f,enumerable:!0,configurable:!0})}catch(g){console.log(g)}}Object.prototype.watch=customObjectProtoTypeWatch;function size(a){try{var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}catch(d){console.log(d)}}function $(a){return document.getElementById(a)}function toBool(a){return"true"==a}
function blankNullorUndefined(a){try{if("undefined"===typeof a||null==a||"string"===typeof a&&""==a.trim())return!0;if("string"===typeof a)return!1}catch(b){console.log(b)}}function coalesce(a,b){try{return blankNullorUndefined(a)?b:a}catch(c){console.log(c)}}function IsNumeric(a){try{return!isNaN(parseFloat(a))&&isFinite(a)}catch(b){console.log(b)}}
(function(){function a(){var a=Array(1E3),c=!1,d=0;return{write:function(e){e&&(a[d]=e,d++,1E3<=d&&(d=0,c=!0),console.log(e))},replay:function(){var e=[],f=0;if(1==c)for(var g=d;1E3>g;++g,++f)e[f]=a[j];for(g=0;g<d;++g,++f)e[f]=a[g];return e.join("")},clear:function(){d=0;c=!1}}}document.addEventListener("RDPInit",function(b){try{b.detail.prototype.logger=a()}catch(c){console.log(c)}})})();
(function(){var a=function(a){this.callback=a;this.key="mru";this.ready=!1;this._maxSavedMRUs=50;this._values={MRUs:[],MRU_Version:2,UserNames:{},Passwords:{}};this.save=function(){try{var a=JSON.stringify(this._values),b={};b[this.key]=a;"undefined"!==typeof chrome.storage&&chrome.storage.local.set(b,function(){})}catch(e){console.log(e)}};this.Populate=function(a){try{var b="";chrome.storage&&"undefined"!==typeof a&&(b=a.mru);if(!blankNullorUndefined(b)){var e=JSON.parse(b),f;for(f in e)if(this._values.hasOwnProperty(f)){var g=
e[f];blankNullorUndefined(g)||(this._values[f]=g)}}this.save();this.ready=!0}catch(k){console.log(k)}};this._ready=function(a,b,e){try{!0===e&&void 0!==this.callback&&null!==this.callback&&this.callback()}catch(f){console.log(f)}};this.watch("ready",this._ready);this.addMRU=function(a,b,e){try{if(!blankNullorUndefined(a)){blankNullorUndefined(b)&&(b="");if(-1<this._values.MRUs.indexOf(a)){var f=this._values.MRUs.indexOf(a);this._values.MRUs.splice(f,1)}this._values.MRUs.push(a);this._values.UserNames[a]=
b;for(this._values.Passwords[a]=e;this._values.MRUs>this._maxSavedMRUs;)this._values.MRUs.splice(0,1);a={};e={};for(f=0;f<this._values.MRUs.length;f++){var g=this._values.MRUs[f],k=this._values.UserNames[g];blankNullorUndefined(k)&&(k="");a[g]=k;var l=this._values.Passwords[g];blankNullorUndefined(l)&&(l="");e[g]=l}this._values.UserNames=a;this._values.Passwords=e}this.save()}catch(p){console.log(p)}};this.ClearPasswords=function(){try{this._values.Passwords={},this.save()}catch(a){console.log(a)}};
this.getUserNameFromAddress=function(a){try{var b="";blankNullorUndefined(a)||(b=this._values.UserNames[a]);blankNullorUndefined(b)&&(b="");return b}catch(e){console.log(e)}};this.getPasswordFromAddress=function(a){try{var b="";blankNullorUndefined(a)||(b=this._values.Passwords[a]);blankNullorUndefined(b)&&(b="");return b}catch(e){console.log(e)}};this._MRUList=function(){return this._values.MRUs};this.getMRUList=function(){try{var a=this._MRUList();a.reverse();return a}catch(b){console.log(b)}}};
document.addEventListener("RDPInit",function(b){try{b.detail.prototype.MRUObject=a}catch(c){console.log(c)}})})();
(function(){var a={constants:{darkCover:"popupManager_darkCover_div",darkCoverStyle:"position:absolute;top:0px;left:0px;padding-right:0px;padding-bottom:0px;background-color:#000000;opacity:0.5;-moz-opacity:0.5;filter:alpha(opacity=0.5);z-index:10000;width:100%;height:100%;",openidSpec:{identifier_select:"http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select",namespace2:"http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0"}},getWindowInnerSize:function(){var a=0,c=0,d=null;"innerWidth"in window?(a=
window.innerWidth,c=window.innerHeight):("BackCompat"===window.document.compatMode&&"body"in window.document?d=window.document.body:"documentElement"in window.document&&(d=window.document.documentElement),null!==d&&(a=d.offsetWidth,c=d.offsetHeight));return[a,c]},getParentCoords:function(){var a=0,c=0;"screenLeft"in window?(a=window.screenLeft,c=window.screenTop):"screenX"in window&&(a=window.screenX,c=window.screenY);return[a,c]},getCenteredCoords:function(a,c){var d=this.getWindowInnerSize(),e=
this.getParentCoords();return[e[0]+Math.max(0,Math.floor((d[0]-a)/2)),e[1]+Math.max(0,Math.floor((d[1]-c)/2))]},darkenScreen:function(){var a=window.document.getElementById(RDPHelper.popupManager.constants.darkCover);a||(a=window.document.createElement("div"),a.id=RDPHelper.popupManager.constants.darkCover,a.setAttribute("style",RDPHelper.popupManager.constants.darkCoverStyle),window.document.body.appendChild(a));a.style.visibility="visible"},createPopupOpener:function(a){var c=null,d=null,e=this,
f="onCloseHandler"in a&&"function"===typeof a.onCloseHandler?a.onCloseHandler:null,g="urlToOpen"in a?a.urlToOpen:null,k=function(){if(!d||d.closed){null!==c&&(window.clearInterval(c),c=null);var a=window.document.getElementById(RDPHelper.popupManager.constants.darkCover);a&&(a.style.visibility="hidden");null!==f&&f();d=null}};return{popup:function(a,b){var f=e.getCenteredCoords(a,b);d=window.open(g,"","width="+a+",height="+b+",status=1,location=1,resizable=yes,left="+f[0]+",top="+f[1]);c=window.setInterval(k,
80);return!0},getGoogleAuthUrl:function(){return g},closePopup:function(){null!==d&&d.close()}}}};document.addEventListener("RDPInit",function(b){b.detail.prototype.popupManager=a})})();function popupResponse(a){try{popupResponse2(a,!0)}catch(b){console.log(b)}}
function popupResponse2(a,b){try{var c=0;null!=ChromerdpModule&&b&&(c=parseInt($(popupIDs.callback).value));4!=c&&-1!=c&&popupPosition(popupState.hide);if(null!=ChromerdpModule)if(0<c){var d=[];d.push(c);"undefined"!==typeof a&&"NaN"!=parseInt(a)&&0<parseInt(a)?d.push("1"):d.push("0");for(var c=[],e=getOptionalFieldArray(),f=0;f<e.length;f++){var g=e[f];g&&g.visible()&&(c.push(g.id),c.push(g.valueEl.value))}0<c.length&&d.push(join(c));sendMessage(command.popup,d)}else if(0==c)sendMessage(command.popup);
else switch(c){case -1:saveSettings(a)&&popupPosition(popupState.hide);break;case -2:$(ID.contents).classList.add(cssClass.busy);$(ID.prompt).innerText="Processing...";sendMessage(command.clearSSLCache);break;case -1001:showConnectingResponse(a)}}catch(k){console.log(k)}}function screenSizeDropdownValueChanged(a){try{toggleCustomScreenSizeRequirement(a.target.value)}catch(b){console.log(b)}}
function toggleCustomScreenSizeRequirement(a){try{var b=$(input.ScreenWidth),c=$(input.ScreenHeight);"Custom"==a?(showObject(ID.customScreenSize),b.addEventListener("change",validateCustomScreenSize),c.addEventListener("change",validateCustomScreenSize),b.required=!0,c.required=!0):(hideObject(ID.customScreenSize),b.removeEventListener("change",validateCustomScreenSize),c.removeEventListener("change",validateCustomScreenSize),b.required=!1,c.required=!1)}catch(d){console.log(d)}}
function validateCustomScreenSize(a){try{a.target.style.borderColor=a.target.validity.valid?"":"red"}catch(b){console.log(b)}}
function validateSettingsOnSave(){try{var a=!0,b=$(input.ScreenWidth);b.required&&!b.validity.valid?(a=!1,b.style.borderColor="red"):b.style.borderColor="";b=$(input.ScreenHeight);b.required&&!b.validity.valid?(a=!1,b.style.borderColor="red"):b.style.borderColor="";b=$(input.ComputerName);b.required&&!b.validity.valid?(a=!1,b.style.borderColor="red"):b.style.borderColor="";return a}catch(c){console.log(c)}}
function saveSettings(a){try{if(blankNullorUndefined(a))return!0;if(!validateSettingsOnSave())return!1;a=null;a=$(input.ScreenSize);controlValue=a.options[a.selectedIndex].value;settingsObj.values.screensize=controlValue.toString();"Custom"==controlValue&&(a=$(input.ScreenHeight),controlValue=a.value,settingsObj.values.customScreenHeight=controlValue.toString(),a=$(input.ScreenWidth),controlValue=a.value,settingsObj.values.customScreenWidth=controlValue.toString());a=$(input.ScreenDepth);controlValue=
a.options[a.selectedIndex].value;settingsObj.values.screendepth=controlValue.toString();a=$(input.Language);controlValue=a.options[a.selectedIndex].value;settingsObj.values.language=controlValue.toString();a=$(input.Keyboard);controlValue=a.options[a.selectedIndex].value;settingsObj.values.keyboard=controlValue.toString();a=$(input.ComputerName);controlValue=a.value;settingsObj.values.computername=controlValue.toString();a=$(input.SSHTunnel);controlValue=a.checked;settingsObj.values.allowssh=controlValue.toString();
a=$(input.AllowNonNLAConnections);controlValue=a.checked;settingsObj.values.allowNonNLA=controlValue.toString();a=$(input.UseTcpNoDelay);controlValue=a.checked;settingsObj.values.useTcpNoDelay=controlValue.toString();a=$(input.StorePasswords);controlValue=a.checked;settingsObj.values.storepasswords=controlValue.toString();a=$(input.AdminConsole);controlValue=a.checked;env.adminConsole;a=$(input.DebugLevel);controlValue=a.options[a.selectedIndex].value;settingsObj.values.debugLevel=parseInt(controlValue);
env.debugLevel=settingsObj.values.debugLevel;a=$(input.ShowWallpaper);controlValue=a.checked;settingsObj.values.showwallpaper=controlValue.toString();a=$(input.TimeZone);controlValue=a.options[a.selectedIndex].value;settingsObj.values.timeZone=controlValue.toString();a=$(input.DisableFullWindowDrag);controlValue=a.checked;settingsObj.values.disableFullWindowDrag=controlValue.toString();a=$(input.DisableMenuAnimations);controlValue=a.checked;settingsObj.values.disableMenuAnimations=controlValue.toString();
a=$(input.DisableTheming);controlValue=a.checked;settingsObj.values.disableTheming=controlValue.toString();a=$(input.DisableCursorShadow);controlValue=a.checked;settingsObj.values.disableCursorShadow=controlValue.toString();a=$(input.DisableCursorBlinking);controlValue=a.checked;settingsObj.values.disableCursorBlinking=controlValue.toString();a=$(input.EnableFontSmoothing);controlValue=a.checked;settingsObj.values.enableFontSmoothing=controlValue.toString();a=$(input.EnableDesktopComposition);controlValue=
a.checked;settingsObj.values.enableDesktopComposition=controlValue.toString();settingsObj.save();"true"!=settingsObj.values.storepasswords&&(bookmarkObj.ClearPasswords(),mruObj.ClearPasswords());sendEnvironment();return!0}catch(b){console.log(b)}}
function showSettings(){try{requestCertificates();var a=$(ID.settings),b=settingsObj.values.screensize,c=settingsObj.values.customScreenWidth,d=settingsObj.values.customScreenHeight,e=settingsObj.values.screendepth,f=settingsObj.values.language,g=settingsObj.values.keyboard,k=settingsObj.values.timeZone,l=settingsObj.values.computername,p="true"==settingsObj.values.allowssh?!0:!1,n="true"==settingsObj.values.allowNonNLA?!0:!1,u="true"==settingsObj.values.useTcpNoDelay?!0:!1,r="true"==settingsObj.values.storepasswords?
!0:!1,q="true"==settingsObj.values.showwallpaper?!0:!1,x="true"==settingsObj.values.disableFullWindowDrag?!0:!1,t="true"==settingsObj.values.disableMenuAnimations?!0:!1,m="true"==settingsObj.values.disableTheming?!0:!1,h="true"==settingsObj.values.disableCursorShadow?!0:!1,A="true"==settingsObj.values.disableCursorBlinking?!0:!1,z="true"==settingsObj.values.enableFontSmoothing?!0:!1,v="true"==settingsObj.values.enableDesktopComposition?!0:!1,w=settingsObj.values.debugLevel;a.classList.remove(cssClass.nodisplay);
blankNullorUndefined(b)||($(input.ScreenSize).value=b,toggleCustomScreenSizeRequirement(b));blankNullorUndefined(c)||($(input.ScreenWidth).value=c);blankNullorUndefined(d)||($(input.ScreenHeight).value=d);blankNullorUndefined(e)||($(input.ScreenDepth).value=e);blankNullorUndefined(f)||($(input.Language).value=f);blankNullorUndefined(g)||($(input.Keyboard).value=g);blankNullorUndefined(l)||($(input.ComputerName).value=l);blankNullorUndefined(k)||($(input.TimeZone).value=k);-1==$(input.TimeZone).selectedIndex&&
($(input.TimeZone).value=-1);$(input.SSHTunnel).checked=p;$(input.AllowNonNLAConnections).checked=n;$(input.UseTcpNoDelay).checked=u;$(input.StorePasswords).checked=r;$(input.ShowWallpaper).checked=q;$(input.DisableFullWindowDrag).checked=x;$(input.DisableMenuAnimations).checked=t;$(input.DisableTheming).checked=m;$(input.DisableCursorShadow).checked=h;$(input.DisableCursorBlinking).checked=A;$(input.EnableFontSmoothing).checked=z;$(input.EnableDesktopComposition).checked=v;for(var y=$(input.DebugLevel),
a=y.selectedIndex=0;a<y.options.length;a++)if(y.options[a].value==w){y.selectedIndex=a;break}setTab(ID.settings,0)}catch(C){console.log(C)}}
function showcontactus(){try{console.log(window.navigator.userAgent);var a=$(ID.popup_contactus),b=$(ID.popup_email_showlog),c=$(ID.popup_email_log),d=$(ID.popup_email_log_copytoclipboard),e=chrome.runtime.getManifest().version,f="Unknown";try{f=window.navigator.appVersion.match(/Chrome\/(.*?) /)[1]}catch(p){console.log(p)}var g=function(){c.classList.add(cssClass.nodisplay);d.classList.add(cssClass.nodisplay);b.checked&&(c.classList.remove(cssClass.nodisplay),d.classList.remove(cssClass.nodisplay));
popupReposition(!0)},k=function(a){a.AddItems([{type:"text/plain",value:c.innerHTML}])};b.checked=!1;b.onclick=g;d.onclick=function(){null!=chrome.runtime&&chrome.runtime.getBackgroundPage(k)};var e="See options to configure message logging.\nChrome RDP "+e+" ----- Chrome OS "+f+"\n'Moderate' is recommended for providing an initial report.\nHigher levels may contain confidential information.\nLogs are not presisted between restarts.\n",l=RDPHelper.logger.replay(),e=l&&l.length&&0<l.length?e+"<<begin log: "+
Date().toLocaleString()+">>\n"+l:e+"<<empty log: "+Date().toLocaleString()+">>\n";c.innerHTML=e;g();a.classList.remove(cssClass.nodisplay)}catch(p){console.log(p)}}
function showConnecting(){try{var a=$(ID.popup_connecting),b=$(ID.popup_connecting_busy_indicator),c=$(ID.popup_connecting_timeout_message);b.classList.remove(cssClass.nodisplay);c.classList.add(cssClass.nodisplay);intervals.connecting_timedout=setTimeout(function(){b.classList.add(cssClass.nodisplay);c.classList.remove(cssClass.nodisplay);sendMessage(command.disconnect)},12E3);a.classList.remove(cssClass.nodisplay)}catch(d){console.log(d)}}
function showConnectingResponse(a){try{clearTimeout(intervals.connecting_timedout),a&&sendMessage(command.disconnect)}catch(b){console.log(b)}}function showCrash(){try{var a=$(ID.popup_crash),b=$(input.submitButton),c=$(input.restartButton);b.onclick=function(){showcontactus()};c.onclick=function(a){try{chrome.runtime.reload()}catch(b){console.log(b)}};a.classList.remove(cssClass.nodisplay)}catch(d){console.log(d)}}
function showAlert(a){try{showPopUp(null,a,null,"OK",null,null)}catch(b){console.log(b)}}function showPopUp(a,b,c,d,e,f){showPopUp2(a,b,c,d,e,f,0)}
function showPopUp2(a,b,c,d,e,f,g){try{$(popupIDs.popup);var k=$(popupIDs.head),l=$(popupIDs.btnYes),p=$(popupIDs.btnSpacer),n=$(popupIDs.btnNo),u=$(popupIDs.callback),r=$(ID.settings),q=$(ID.popup_contactus),x=$(ID.popup_connecting),t=$(ID.popup_crash),m=$(popupIDs.body),h=$(popupIDs.optional_inputs),A=$(popupIDs.popup_auth_section);""==b&&""==c?(m.style.display="none",A.style.display="block"):(m.style.display="block",A.style.display="none");k.classList.add(cssClass.nodisplay);l.classList.add(cssClass.nodisplay);
p.classList.add(cssClass.nodisplay);n.classList.add(cssClass.nodisplay);r.classList.add(cssClass.nodisplay);q.classList.add(cssClass.nodisplay);x.classList.add(cssClass.nodisplay);t.classList.add(cssClass.nodisplay);m.classList.add(cssClass.nodisplay);h.classList.add(cssClass.nodisplay);a=blankNullorUndefined(a)?"none":a;blankNullorUndefined(c)||$(popupIDs.head).classList.remove(cssClass.nodisplay);c=blankNullorUndefined(c)?defaultPopupTitle:c;$(popupIDs.head).innerText=c;$(popupIDs.body).innerHTML=
b;u.value=a;blankNullorUndefined(d)||(l.classList.remove(cssClass.nodisplay),l.innerText=d,l.focus());blankNullorUndefined(e)||(n.classList.remove(cssClass.nodisplay),n.innerText=e,n.focus());blankNullorUndefined(d)||blankNullorUndefined(e)||p.classList.remove(cssClass.nodisplay);if(f&&0<f.length){h.classList.remove(cssClass.nodisplay);for(var z=getOptionalFieldArray(),v=0;v<z.length;v++){var w=z[v];w&&w.visible()&&w.containerEl.classList.add(cssClass.nodisplay)}for(v=0;v<f.length;v+=3)w=z.filter(function(a){return a.id==
f[v]}).shift(),w.containerEl.classList.remove(cssClass.nodisplay),w.captionEl.innerText=f[v+1],w.valueEl.value=f[v+2];b=!1;var y=null;if("2"==a&&3==z.length){var C=z[0],B=z[1];C.hasValue()?(B.hasValue()?(B.valueEl.focus(),B.valueEl.setSelectionRange(B.valueEl.value.length,B.valueEl.value.length)):B.valueEl.focus(),y=B):(C.valueEl.focus(),y=C);b=!0;0<C.length&&0<B.length&&(watchUseResponse=!0)}else{for(v=0;v<z.length;v++)if(w=z[v]){var D=w.visible(),G=w.hasValue();if(D&&!G){w.valueEl.focus();y=w;b=
!0;break}}if(!b)for(v=z.length-1;0<=v;v--)if(w=z[v])if(D=w.visible()){w.valueEl.focus();y=w;b=!0;break}}}$(popupIDs.password_store).style.display="2"==a&&"true"==settingsObj.values.storepasswords?"table-row":"none";var E=$(popupIDs.refreshlink);E&&E.addEventListener("click",function(a){history.go(0)});_popupID=a;if(0>a)switch(a){case -1:showSettings();break;case -1E3:showcontactus();break;case -1001:showConnecting();break;case -1002:showCrash()}else{if(0!=g){showPopUp2_Callback(g);return}m.classList.remove(cssClass.nodisplay)}popupPosition(popupState.show);
y&&y.valueEl&&y.valueEl.focus&&y.valueEl.focus();y&&y.focus&&y.focus()}catch(F){console.log(F)}}function showPopUp2_Callback(a){popupResponse(a)}function OptionalField(a,b){try{this.id=a,this.containerEl=$(b),this.captionEl=$(b+"_caption"),this.valueEl=$(b+"_value"),this.valueEl.addEventListener("keydown",popupKeyDown)}catch(c){console.log(c)}}OptionalField.prototype.visible=function(){try{return!this.containerEl.classList.contains(cssClass.nodisplay)}catch(a){console.log(a)}};
OptionalField.prototype.hasValue=function(){try{return 0<this.valueEl.value.length}catch(a){console.log(a)}};function getOptionalFieldArray(){try{var a=new OptionalField("1",popupIDs.text1),b=new OptionalField("2",popupIDs.password),c=new OptionalField("3",popupIDs.domain);return[a,b,c]}catch(d){console.log(d)}}var popupState={hide:0,show:1},_popupState=popupState.hide,_popupID=0;
function popupPosition(a,b){try{if(!signingin){var c=$(popupIDs.popup),d=$(ID.black);if(a==popupState.show){c.classList.remove(cssClass.scale0);c.classList.add(cssClass.scale100);if(null==b||1==b)d.classList.contains(cssClass.opacity0)&&d.classList.remove(cssClass.opacity0),d.classList.contains(cssClass.opacity50)||d.classList.add(cssClass.opacity50);var e=-(c.offsetHeight/2),f=-(c.offsetWidth/2),e=e-0,f=f-0;c.style.top="45%";c.style.right="50%";c.style.marginTop=e+"px";c.style.marginRight=f+"px"}else c.classList.remove(cssClass.scale100),
c.classList.add(cssClass.scale0),(null==b||1==b)&&0>_popupID&&(d.classList.contains(cssClass.opacity50)&&d.classList.remove(cssClass.opacity50),d.classList.contains(cssClass.opacity0)||d.classList.add(cssClass.opacity0)),c.style.removeProperty("top"),c.style.removeProperty("right"),c.style.removeProperty("margin-top"),c.style.removeProperty("margin-right"),$("popupContainer").style.display="none";_popupState=a;a==popupState.show&&popupReposition(!0)}}catch(g){console.log(g)}}
function popupReposition(a){try{if(_popupState==popupState.show){var b=$("popupContainer"),c=$(popupIDs.popup),d=appWindowOrPepperDummy();b.style.display="";var e=487,f=435,g=!1;0!=c.clientWidth&&(e=c.clientWidth,g=!0);b.style.width=e+"px";0!=c.clientHeight&&(f=c.clientHeight,g=!0);b.style.height=f+"px";b.style.overflow="";var k=b.offsetLeft,c=!1;0>k&&(c=!0);var e=k+e+1,l=!1;e>d.innerBounds.width&&(l=!0);var p=Math.round(d.innerBounds.width/2-(e-k)/2);0>p&&(p=0);if(c||l||a)b.style.left=p+"px",k=p;
var n=Math.round(d.innerBounds.height/2-f/2);0>n&&(n=0);var u=d.innerBounds.height-f;200<u&&(u=Math.round((u-200)/2),100<u&&(u=100),0<u&&(n-=u));var r=b.offsetTop;a&&(b.style.top=n+"px",r=n);f=r+f-r;g||setTimeout(function(){popupReposition(a)},100)}}catch(q){console.log(q)}}function setLicenseURL(a){try{$(ID.license_link).setAttribute("href",a)}catch(b){console.log(b)}}function doLicenseAuthentication(){try{$(ID.license_link).click()}catch(a){console.log(a)}}var UIprocessed=!1;
function animateShowActivateButton(a){try{0!=$(ID.activate).offsetTop||a?a&&(clearAnimationClasses($(ID.activate)),$(ID.activate).classList.add(cssClass.homeInFromTop),$(ID.activate).classList.add(cssClass.marginbottom60)):(clearAnimationClasses($(ID.activate)),$(ID.activate).classList.add(cssClass.homeOutToTop),$(ID.activate).classList.remove(cssClass.marginbottom60))}catch(b){console.log(b)}}
function animateActivateOption(a,b){try{var c=a.offsetLeft;clearAnimationClasses(a);clearAnimationClasses(b);0==c?(a.classList.add(cssClass.homeOutToRight),b.classList.add(cssClass.homeInFromLeft)):(a.classList.add(cssClass.homeInFromLeft),b.classList.add(cssClass.homeOutToRight))}catch(d){console.log(d)}}
function clearAnimationClasses(a){try{a.classList.remove(cssClass.homeInFromLeft),a.classList.remove(cssClass.homeInFromLeftFinal),a.classList.remove(cssClass.homeInFromTop),a.classList.remove(cssClass.homeInFromTopFinal),a.classList.remove(cssClass.homeOutToRight),a.classList.remove(cssClass.homeOutToRightFinal),a.classList.remove(cssClass.homeOutToTop),a.classList.remove(cssClass.homeOutToTopFinal)}catch(b){console.log(b)}}
function requestCertificates(){try{var a=$(input.CertificateSelect);0>=a.options.length&&(a.options[a.options.length]=new Option("Loading...",0));a.disabled=!0;$(input.CertificateDelete).disabled=!0;$(input.ClearSSLCache).disabled=!0;sendMessage(command.certs_request)}catch(b){console.log(b)}}
function returnedCertificateHandler(a){try{var b=a.split(command.delimeterArgs);b.sort();var c=$(input.CertificateSelect);c.innerHTML="";for(index in b)IsNumeric(index)&&""!=b[index]&&(c.options[c.options.length]=new Option(b[index],index));c.disabled=!1;$(input.CertificateDelete).disabled=!1;$(input.ClearSSLCache).disabled=!1}catch(d){console.log(d)}}function returnedCertificateDeleteHandler(){try{requestCertificates()}catch(a){console.log(a)}}
function certificateDeleteAllButtonClickHandler(a){try{if(!simplePopupShowing){var b=$(input.CertificateSelect);$(input.CertificateDelete);$(input.ClearSSLCache);0==b.options.length?simplePopup_showOK("No items are available for deletion.",null):simplePopup_showOKCancel("Are you sure you want to delete all listed item(s)?",certificateDeleteAllButtonClickHandler_ok,null)}}catch(c){console.log(c)}}
function certificateDeleteAllButtonClickHandler_ok(){try{sendMessage(command.clearSSLCache);for(var a=$(input.CertificateSelect);0<a.options.length;)a.options.remove(0)}catch(b){console.log(b)}}
function certificateDeleteButtonClickHandler(a){try{if(!simplePopupShowing){var b=$(input.CertificateSelect);$(input.CertificateDelete);$(input.ClearSSLCache);0==b.options.length?simplePopup_showOK("No items are available for deletion.",null):"undefined"==typeof b.options[b.selectedIndex]?simplePopup_showOK("No items have been selected.",null):simplePopup_showOKCancel("Are you sure you want to delete the selected item(s)?",certificateDeleteButtonClickHandler_ok,null)}}catch(c){console.log(c)}}
function certificateDeleteButtonClickHandler_ok(){try{var a=$(input.CertificateSelect),b=$(input.CertificateDelete),c=$(input.ClearSSLCache),d=a.options[a.selectedIndex].text;a.disabled=!0;b.disabled=!0;c.disabled=!0;sendMessage(command.cert_delete,d)}catch(e){console.log(e)}}
function storePasswordsClickHandler(){try{1==$(input.StorePasswords).checked&&simplePopup_showOKCancel("WARNING: While stored passwords are encrypted, there is still a potential security risk. By enabling this functionality, you are agreeing to store passwords at your own risk.",null,storePasswordsClickHandler_cancel)}catch(a){console.log(a)}}function storePasswordsClickHandler_cancel(){try{$(input.StorePasswords).checked=!1}catch(a){console.log(a)}}
var simplePopup_callback_ok=null,simplePopup_callback_cancel=null;function simplePopup_init(){try{var a=$("simplePopup_button_ok"),b=$("simplePopup_button_cancel");a.addEventListener("click",simplePopup_button_ok_click);b.addEventListener("click",simplePopup_button_cancel_click);simplePopup_callback_cancel=simplePopup_callback_ok=null;simplePopup_show("Some really long starter text to help initialize the size of this popup",!0,null,!0,null);simplePopup_hide()}catch(c){console.log(c)}}
function simplePopup_showOK(a,b){try{simplePopup_show(a,!0,b,!1,null)}catch(c){console.log(c)}}function simplePopup_showCancel(a,b){try{simplePopup_show(a,!1,null,!0,b)}catch(c){console.log(c)}}function simplePopup_showOKCancel(a,b,c){try{simplePopup_show(a,!0,b,!0,c)}catch(d){console.log(d)}}var simplePopupShowing=!1;
function simplePopup_show(a,b,c,d,e){try{tabViewDisabled=!0;simplePopup_callback_ok=c;simplePopup_callback_cancel=e;var f=$("simplePopup_div"),g=$("simplePopup_message_section"),k=$("simplePopup_label_body"),l=$("simplePopup_cell_ok"),p=$("simplePopup_cell_cancel");f.classList.add(cssClass.simplePopup_show);f.classList.remove(cssClass.simplePopup);g.style.display="block";l.style.display=1==b?"table-cell":"none";p.style.display=1==d?"table-cell":"none";k.innerHTML=a;f.style.display="block";var n=-(f.offsetHeight/
2),u=f.offsetWidth/2,r=-(f.offsetWidth/2),n=n-50;f.style.top="50%";f.style.right="50%";f.style.marginTop=n+"px";f.style.marginLeft=u+"px";f.style.marginRight=r+"px";simplePopupShowing=!0}catch(q){console.log(q)}}
function simplePopup_hide(){try{simplePopupShowing=!1;simplePopup_callback_cancel=simplePopup_callback_ok=null;var a=$("simplePopup_div");a.style.display="none";a.classList.remove(cssClass.simplePopup_show);a.classList.add(cssClass.simplePopup);tabViewDisabled=!1}catch(b){console.log(b)}}function simplePopup_button_ok_click(){try{null!=simplePopup_callback_ok&&simplePopup_callback_ok(),simplePopup_hide()}catch(a){console.log(a)}}
function simplePopup_button_cancel_click(){try{null!=simplePopup_callback_cancel&&simplePopup_callback_cancel(),simplePopup_hide()}catch(a){console.log(a)}}
(function(){var a=function(a){this.callback=a;this.key="settings";this.ready=!1;this.values={screensize:"Automatic",screendepth:"32",language:"0x00000409",computername:"ChromeRDP",allowssh:"false",allowNonNLA:"false",useTcpNoDelay:"false",storepasswords:"false",showwallpaper:"false",customScreenWidth:800,customScreenHeight:600,debugLevel:0,disableFullWindowDrag:"false",disableMenuAnimations:"false",disableTheming:"false",disableCursorShadow:"false",disableCursorBlinking:"false",enableFontSmoothing:"false",
enableDesktopComposition:"false",keyboard:"0x00000004",timeZone:-1};this.save=function(){try{var a=JSON.stringify(this.values),b={};b[this.key]=a;"undefined"!==typeof chrome.storage&&chrome.storage.local.set(b,function(){})}catch(e){console.log(e)}};this.Populate=function(a){try{var b="";chrome.storage&&"undefined"!==typeof a&&(b=a.settings);if(!blankNullorUndefined(b)){var e=JSON.parse(b),f;for(f in e)if(this.values.hasOwnProperty(f)){var g=e[f];blankNullorUndefined(g)||(this.values[f]=g)}}if(!this.values.computername||
0===this.values.computername.length||"ChromeRDP"===this.values.computername){var k=this.values;a="";for(b=6;0<b;--b)a+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"[Math.floor(62*Math.random())];k.computername="ChromeRDP"+a}this.save();this.ready=!0}catch(l){console.log(l)}};this._ready=function(a,b,e){try{!0===e&&void 0!==this.callback&&null!==this.callback&&this.callback()}catch(f){console.log(f)}};this.watch("ready",this._ready)};document.addEventListener("RDPInit",function(b){try{b.detail.prototype.SettingsObject=
a}catch(c){console.log(c)}})})();
(function(){function a(){return{width:0,height:0,left:0,top:0,isMaximized:!1,isMinimized:!1,isFullscreen:!1,isAutomatic:!1}}function b(){function b(c){try{m="undefined"===typeof c||"undefined"===typeof c.screenSettings||null==c.screenSettings&&"undefined"==c.screenSettings?a():c.screenSettings}catch(d){logException(d)}}function d(a){try{null==m?setTimeout(function(){d(a)},100):setTimeout(a,100)}catch(b){logException(b)}}function e(a,b){try{return env.width=a,env.height=b,env.width-=env.width%4,env.width}catch(c){logException(c)}}
function f(){try{var a=$(ID.frame),b=$(ID.black);null!=h().innerBounds.minWidth&&0<h().innerBounds.minWidth&&null!=h().innerBounds.minHeight&&0<h().innerBounds.minHeight&&(h().innerBounds.width!=h().innerBounds.minWidth&&(h().innerBounds.width=h().innerBounds.minWidth),h().innerBounds.height!=h().innerBounds.minHeight&&(h().innerBounds.height=h().innerBounds.minHeight));b.style.width=a.scrollHeight>a.clientHeight?a.clientWidth+1+"px":"100%";b.style.height=a.scrollWidth>a.clientWidth?a.clientHeight+
1+"px":"100%";_popupState==popupState.show&&popupReposition(!0)}catch(c){logException(c)}}function g(a,b){var c=function(){h().onRestored.removeListener(c);a.isFullscreen?k(a,b):a.isMaximized?l(a,b):a.isMinimized?p(a,b):n(a,b)};h().onRestored.addListener(c);h().restore()}function k(a,b){var c=function(){h().onFullscreened.removeListener(c);a.isFullscreen?n(a,b):a.isMaximized?l(a,b):a.isMinimized?p(a,b):g(a,b)};h().onFullscreened.addListener(c);h().fullscreen()}function l(a,b){var c=function(){h().onMaximized.removeListener(c);
a.isFullscreen?k(a,b):a.isMaximized?n(a,b):a.isMinimized?p(a,b):g(a,b)};h().onMaximized.addListener(c);h().maximize()}function p(a,b){var c=function(){h().onMinimized.removeListener(c);a.isFullscreen?k(a,b):a.isminimized?l(a,b):a.isMinimized?n(a,b):g(a,b)};h().onMinimized.addListener(c);h().minimize()}function n(a,b){a.isFullscreen?e(h().outerBounds.width,h().outerBounds.height):a.isMaximized?(e(h().innerBounds.width,h().innerBounds.height),u(h().innerBounds.width,h().innerBounds.height)):(e(a.width,
a.height),u(a.width,a.height));setTimeout(f,250);b()}function u(a,b){a&&b?(h().innerBounds.setMinimumSize(a,b),h().innerBounds.setMaximumSize(a,b)):(h().innerBounds.setMinimumSize(null,null),h().innerBounds.setMaximumSize(null,null),h().outerBounds.setMinimumSize(null,null),h().outerBounds.setMaximumSize(null,null))}function r(a,b){u(null,null);h().isFullscreen()?a.isFullscreen||a.isAutomatic?n(a,b):g(a,b):h().isMaximized()?a.isMaximized||a.isAutomatic?n(a,b):g(a,b):h().isMinimized()?a.isMinimized||
a.isAutomatic?n(a,b):g(a,b):a.isFullscreen?k(a,b):a.isMaximized?l(a,b):a.isMinimized?p(a,b):n(a,b)}var q=!1,x=!0,t=a(),m=null,h=appWindowOrPepperDummy;null==h().id?logMessage("started window:id=null"):logMessage("started window:id="+h().id);chrome.app&&chrome.app.window&&chrome.app.window.current().onBoundsChanged.addListener(function(){try{f();if(q){if(t.isFullscreen&&!h().isFullscreen()){h().fullscreen();setTimeout(popup_DisabledResize,10);return}if(t.isMaximized&&!h().isMaximized()&&!h().isMinimized()){h().maximize();
setTimeout(popup_DisabledResize,10);return}if(!t.isFullscreen&&!t.isMaximized&&(h().isFullscreen()||h().isMaximized())){h().restore();setTimeout(popup_DisabledResize,10);return}}if(!q){if(null!==m||"undefined"==m)m=a();m.isFullscreen=h().isFullscreen();m.isMaximized=h().isMaximized();m.isMinimized=h().isMinimized();m.isFullscreen||m.isMaximized||m.isMinimized||(m.width=h().innerBounds.width,m.height=h().innerBounds.height,m.left=h().outerBounds.left,m.top=h().outerBounds.top);chrome.storage.local.set({screenSettings:m},
function(){})}}catch(b){logException(b)}});return{isFullscreen:function(){return h().isFullscreen()},started:function(a){a&&"boolean"==typeof a&&(q=a);return q},minimizeScreen:function(a){try{h().isMinimized()||h().minimize()}catch(b){logException(b)}},screenEnableResizing:function(){try{m&&r(m,function(){u(null,null)}),x=!0,q=!1}catch(a){logException(a)}},screenDisableResizing:function(){try{q=!0,x=!1,h().isFullscreen()||u(h().innerBounds.width,h().innerBounds.height)}catch(a){logException(a)}},
toggleFullscreen:function(a){try{if(!x)if(connection==connectionStatus.standby||connection==connectionStatus.disconnected||connection==connectionStatus.disconnecting||connection==connectionStatus.error)this.screenEnableResizing();else{a();return}h().isFullscreen()?h().restore():h().fullscreen()}catch(b){logException(b)}},initSizeFromSettings:function(a){try{try{var b=null;null!=settingsObj&&null!=settingsObj.values&&(b=settingsObj.values.screensize);var c=screen.width-200,d=screen.height-200,e=0,
f=0,g=!1,k=!1,l=!0;"string"!==typeof b&&(b=null);if(!blankNullorUndefined(b))if("Automatic"==b)l=!1,k=!0;else if("Fullscreen"==b)l=!1,g=!0;else if("Custom"==b)l=!1,c=parseInt(settingsObj.values.customScreenWidth),d=parseInt(settingsObj.values.customScreenHeight);else if(-1<b.indexOf(command.delimeter)){var m=b.split(command.delimeter);if(2==m.length){var n=parseInt(m[0]),q=parseInt(m[1]);blankNullorUndefined(n)&&blankNullorUndefined(q)||(l=!1,c=n,d=q)}}l&&blankNullorUndefined(b)&&(b="Automatic",k=
!0,null!=settingsObj&&null!=settingsObj.values&&(settingsObj.values.screensize=b,settingsObj.save()));k&&(c=h().innerBounds.width,d=h().innerBounds.height,g=h().isFullscreen());c-=c%4;e=h().outerBounds.left;f=h().outerBounds.top;t.width=c;t.height=d;t.left=e;t.top=f;t.isFullscreen=g;t.isAutomatic=k}catch(p){logException(p)}r(t,a)}catch(p){logException(p)}},loadSettings:function(a){try{chrome.storage.local.get("screenSettings",b),setTimeout(function(){d(a)},100)}catch(e){logException(e)}}}}document.addEventListener("RDPInit",
function(a){try{a.detail.prototype.ViewPort=b()}catch(d){console.log(d)}})})();
