var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var f=b.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var e=b[c];if(e===a||Object.is(e,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
var lsUiStyle="uiStyle",lsConfirmDeleteCookies="confirmDeleteCookies",lsConfirmRestoreStoredCookies="confirmRestoreStoredCookies",lsRestoreFixExpiration="restoreFixExpiration",lsConfirmDeleteStoredCookies="confirmDeleteStoredCookies",lsFilterDomain="filterDomain",lsFilterName="filterName",lsFilterValue="filterValue",lsRememberFilterCloseTab="rememberFilter",lsPopupHeight="popupHeight",lsPopupWidth="popupWidth",confirmDeleteCookies,confirmRestoreStoredCookies,restoreFixExpiration,confirmDeleteStoredCookies,
filterDomain,filterName,filterValue,rememberFilter,popupHeight,popupWidth,uiStyle=void 0!==localStorage[lsUiStyle]?localStorage[lsUiStyle]:"start";$("#styleLink").attr("href","http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/"+uiStyle+"/jquery-ui.css");var hostPage,allCookies,cookieCheckBoxPrefix="cookieCheckBox-",cookieRowPrefix="cookieRow-",lsSavedCookies="savedCookies",lsMaxSavedCookies="maxSavedCookies",maxSavedCookies;
$(document).ready(function(){aT();hostPage=window.location.pathname.replace(/^.*\/([^\/]*)/,"$1").replace(/\.html/,"");"popup"===hostPage?(a5(),$("input:button").button(),bv(),$("#filterDomainInput").focus(),aQ(),loadCookies(),$("#newExpirationDatePicker").datepicker({changeMonth:!0,changeYear:!0,showOtherMonths:!0,selectOtherMonths:!0,numberOfMonths:2,showButtonPanel:!0}),bk()):"options"===hostPage&&(bc(),$("#saveButton").click(function(){bz();
chrome.extension.getBackgroundPage().aT();return!1}),$("#closeButton").click(function(){bA();return!1}))});function a5(){aZ("#newExpirationHours",24);aZ("#newExpirationMinutes",60);aZ("#newExpirationSeconds",60)}function aZ(a,b){for(var c=0;c<b;c++){var d=c;10>c&&(d="0"+c);$(a).append("'<option value='"+c+"'>"+d+"</option>")}}
function bk(){$("#previousThemeAnchor").click(function(){bF(-1);return!1});$("#nextThemeAnchor").click(function(){bF(1);return!1});$("#styleSelect").change(function(){aR()});$("#loadCookiesAnchor").click(function(){loadCookies();return!1});$("#clearFiltersAnchor").click(function(){bq();return!1});$("#selectAllButton").click(function(){bE()});$(document).on("click","#selectAllCookiesAnchor",function(){bE();$("#saveCookiesErrorSpan").html("");
return!1});$("#selectNoneButton").click(function(){bD()});$("#saveOrRestoreButton").click(function(){bn()});$("#deleteButton").click(function(){aq()});$("#saveSelectedCookiesAnchor").click(function(){aM();return!1});$("#editCookieValueAnchor").click(function(){a0();return!1});$("#filterDomainInput").attr("autofocus","autofocus");$(document).on("click",".cookieDetailsAnchor",function(){var a=$(this).attr("cookieId");aY(a);
return!1});$(document).on("click",".restoreSavedCookiesAnchor",function(){var a=$(this).attr("cookieName");aw(a);return!1});$(document).on("click",".delete_session_anchor",function(){var a=$(this).attr("cookieName"),b=$(this).attr("cookieTitle");az(a,b);return!1})}var filDI="",filNI="",filVI="";
function aQ(){$("#filterDomainInput").keydown(function(a){setTimeout(function(){var b=$("#filterDomainInput")[0].value;13!==a.which&&filDI!==b&&loadCookies();filDI=b},200)});$("#filterNameInput").keydown(function(a){setTimeout(function(){var b=$("#filterNameInput")[0].value;13!==a.which&&filNI!==b&&loadCookies();filNI=b},200)});$("#filterValueInput").keydown(function(a){setTimeout(function(){var b=$("#filterValueInput")[0].value;13!==a.which&&filVI!==b&&loadCookies();filVI=b},200)})}
function bq(){$("#filterDomainInput,#filterNameInput,#filterValueInput").val("");loadCookies()}
function loadCookies(){var a,b;chrome.tabs.query({active:!0,currentWindow:!0},function(c){a=c[0].id;chrome.cookies.getAllCookieStores(function(c){for(var d=0;d<c.length;d++)if(c[d].tabIds.includes(a)){b=c[d].id;break}chrome.cookies.getAll({storeId:b},function(a){filDI=$("#filterDomainInput")[0].value;filNI=$("#filterNameInput")[0].value;filVI=$("#filterValueInput")[0].value;a=bm(a);$("#cookieCountSpan").html(bG(a.length));a.sort(sortDomain);allCookies=a;var b="<table id='tab2'><tr id='row1'><td id='col0b'></td><td id='col1b'><b>Domain</b></td><td id='col2b'><b>Name</b></td><td align='right' id='col3b'><b>Expiration</b></td><td></td></tr>";
if(0===a.length)b+="<tr><td colspan='5'>no cookies returned!</td></tr>";else for(var c=0,d;d=a[c];c++){var e=0==d.domain.search(/^\d*\./);b+="<tr id='"+cookieRowPrefix+c+"'><td><input type='checkbox' id='"+cookieCheckBoxPrefix+c+'\'></td><td class="dname">'+(e?'<span class="tailDot">o</span><span>':"")+d.domain+(e?"</span>":"")+"</td><td class='cname'><a class='cookieDetailsAnchor' cookieId='"+c+"' href=''>"+(d.name||"?")+"</a></td><td name='date' align='right'>"+aG(d.expirationDate)+
"</td><td name='time' align='right'>"+aH(d.expirationDate)+"</td></tr>"}b+="</table>";$("#listDiv").html(b);a=parseInt($("#col1b").width(),10);b=parseInt($("#col2b").width(),10);c=parseInt($("#col3b").width(),10);$("#col0a").attr("width",parseInt($("#col0b").width(),10));$("#col1a").attr("width",a);$("#col2a").attr("width",b);$("#col3a").attr("width",c);$("#row1").hide();$('#cookiesDiv input[type="checkbox"]').shiftSelectable()})})})}
function bm(a){var b=[],c,d,f,e=$("#filterDomainInput"),g=$("#filterNameInput"),h=$("#filterValueInput");a4(e.val());bf(g.val());a8(h.val());try{0<filterDomain.length&&(c=new RegExp(filterDomain,"i")),e[0].classList.remove("error")}catch(k){e[0].classList.add("error")}try{0<filterName.length&&(d=new RegExp(filterName,"i")),g[0].classList.remove("error")}catch(k){g[0].classList.add("error"),g[0].title="Invalid regular expression"}try{0<filterValue.length&&
(f=new RegExp(filterValue,"i")),h[0].classList.remove("error")}catch(k){h[0].classList.add("error")}for(e=0;g=a[e];e++)bx(g,c,d,f)&&b.push(g);return b}function bx(a,b,c,d){return void 0===b&&void 0===c&&void 0===d?!0:void 0!==b&&-1===a.domain.search(b)||void 0!==c&&-1===a.name.search(c)||void 0!==d&&-1===a.value.search(d)?!1:!0}function aW(a,b){return a.length<b?a:a.substring(0,b)+"..."}
function aA(a){if(void 0===a)return"session";var b=new Date(1E3*a);a=b.getDate();var c=b.getMonth()+1,d=b.getFullYear(),f=b.getHours(),e=b.getMinutes();b=b.getSeconds();10>e&&(e="0"+e);10>b&&(b="0"+b);return isNaN(c)||isNaN(a)||isNaN(d)||isNaN(f)||isNaN(e)||isNaN(b)?"":c+"/"+a+"/"+d+" "+f+":"+e+":"+b}
function aG(a){if(void 0===a)return"session";var b=new Date(1E3*a);a=b.getDate();var c=b.getMonth()+1;b=b.getFullYear();return isNaN(c)||isNaN(a)||isNaN(b)?"":c+"/"+a+"/"+b}function aH(a){if(void 0===a)return"";var b=new Date(1E3*a);a=b.getHours();var c=b.getMinutes();b=b.getSeconds();10>c&&(c="0"+c);10>b&&(b="0"+b);return isNaN(a)||isNaN(c)||isNaN(b)?"":a+":"+c+":"+b}
function sortDomain(a,b){var c=bC(a.domain).toLowerCase(),d=bC(b.domain).toLowerCase();if(c<d)return-1;if(c>d)return 1;c=a.domain.toLowerCase();d=b.domain.toLowerCase();if(c<d)return-1;if(c>d)return 1;c=a.name.toLowerCase();d=b.name.toLowerCase();return c<d?-1:c>d?1:0}function bC(a){var b=a.split(".");return 2>=b.length?a:b[b.length-2]+"."+b[b.length-1]}function sortIntDescending(a,b){a=-1*parseInt(a,10);b=-1*parseInt(b,10);return a<b?-1:a>b?1:0}
function aY(a){a=parseInt(a,10);a>=allCookies.length?a=0:0>a&&(a=allCookies.length-1);var b=allCookies[a];$("#currentCookieId").attr("cookieId",a);$("#detailsDomainSpan").html(b.domain);$("#detailsNameSpan").html(b.name);$("#detailsValueDiv").html(b.value);$("#detailsHostOnlySpan").html(b.hostOnly?"true":"false");$("#detailsPathSpan").html(b.path);$("#detailsSecureSpan").html(b.secure?"true":"false");$("#detailsHttpOnlySpan").html(b.httpOnly?"true":"false");$("#detailsSessionSpan").html(b.session?
"true":"false");$("#detailsExpirationDateSpan").html(aA(b.expirationDate));$("#detailsStoreIdSpan").html(b.storeId);$("#cookieDetailsDiv").dialog("destroy").dialog({autoOpen:!1,width:725,modal:!0,buttons:{Previous:function(){aY(a-1)},Next:function(){aY(a+1)},Edit:function(){a0()},Close:function(){$(this).dialog("close")}}});$("#cookieDetailsDiv").dialog("option","title","Cookie Details");$("#cookieDetailsDiv").dialog("open")}
function a0(){var a=parseInt($("#currentCookieId").attr("cookieId"),10);a>=allCookies.length?a=0:0>a&&(a=allCookies.length-1);a=allCookies[a];$("#editDomainSpan").html(a.domain);$("#editNameSpan").html(a.name);$("#editValueCurrentDiv").html(a.value);$("#editValueNewTextArea").val(a.value);var b=$("#editValueNewTextArea").attr("cols");$("#editValueNewTextArea").attr("rows",a.value.length/b+2);$("#editExpirationDateSpan").html(aA(a.expirationDate));a=new Date(aA(a.expirationDate));
$("#newExpirationDatePicker").datepicker("setDate",a);$("#newExpirationHours").val(a.getHours());$("#newExpirationMinutes").val(a.getMinutes());$("#newExpirationSeconds").val(a.getSeconds());$("#editCookieDiv").dialog("destroy").dialog({autoOpen:!1,width:725,modal:!0,buttons:{Save:function(){a6()},Cancel:function(){$(this).dialog("close")}}});$("#editCookieDiv").dialog("option","title","Edit Cookie Value");$("#editCookieDiv").dialog("open")}
function a6(){var a=parseInt($("#currentCookieId").attr("cookieId"),10),b=$("#editValueCurrentDiv").html(),c=String($("#editValueNewTextArea").val());c=$.trim(c);var d=new Date($("#editExpirationDateSpan").html()),f=aJ();if(b!==c||d!==f){var e=allCookies[a];b="http"+(e.secure?"s":"")+"://"+e.domain.replace(/^\./,"")+e.path;var g=f.getTime()/1E3;b={url:b,name:e.name,value:c,path:e.path,secure:e.secure,httpOnly:e.httpOnly,expirationDate:g,storeId:e.storeId};"."==e.domain[0]&&
(b.domain=e.domain);chrome.cookies.set(b,function(){var b=chrome.runtime.lastError;b&&console.info("a6() Error:",b.message);e.value=c;e.expirationDate=g;$("#detailsValueDiv").html(e.value);$("#detailsExpirationDateSpan").html(aA(e.expirationDate));$("#cookieDetailsDiv").dialog("option","maxHeight",600);$("#editCookieDiv").dialog("close");d!==f&&($("#cookieRow-"+a+' > td[name="date"]').html(aG(e.expirationDate)),$("#cookieRow-"+a+' > td[name="time"]').html(aH(e.expirationDate)))})}else $("#editCookieDiv").dialog("close")}
function bE(){$('input[id^="'+cookieCheckBoxPrefix+'"]').attr("checked",!0)}function bD(){$('input[id^="'+cookieCheckBoxPrefix+'"]').attr("checked",!1)}
function aq(){if(confirmDeleteCookies){for(var a=0,b=0;allCookies[b];b++)$("#"+cookieCheckBoxPrefix+b).attr("checked")&&a++;by("Delete Cookies","Are you sure you want to delete the selected cookies?<br/><br/>Selected cookies count: "+a,deleteSelectedCookies,null,null)}else deleteSelectedCookies(!0)}
function deleteSelectedCookies(a){if(a){a=[];for(var b=0,c;c=allCookies[b];b++)$("#"+cookieCheckBoxPrefix+b).attr("checked")&&(a.push(b),bt(b,c));a.sort(sortIntDescending);for(b=0;b<a.length;b++)c=a[b],allCookies.splice(c,1),$("#"+cookieRowPrefix+c).hide();$("#cookieCountSpan").html(bG(allCookies.length));loadCookies()}}function bt(a,b){chrome.cookies.remove({url:"http"+(b.secure?"s":"")+"://"+b.domain+b.path,name:b.name,storeId:b.storeId},function(){})}
function bF(a){a=parseInt($("#styleSelect option:selected").attr("id"),10)+a;23<a&&(a=0);0>a&&(a=23);uiStyle=$("#styleSelect option[id="+a+"]").val();$("#styleSelect").val(String(uiStyle));$("#styleLink").attr("href","http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/"+uiStyle+"/jquery-ui.css");localStorage[lsUiStyle]=uiStyle}
function aR(){uiStyle=$("#styleSelect").val();$("#styleLink").attr("href","http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/"+uiStyle+"/jquery-ui.css");localStorage[lsUiStyle]=uiStyle}
function bn(){var a="",b=$("#filterDomainInput").val(),c=$("#filterNameInput").val(),d=$("#filterValueInput").val();0<b.length&&(a+="Domain: ["+b+"]");0<c.length&&(0<a.length&&(a+=" "),a+="Name: ["+c+"]");0<d.length&&(0<a.length&&(a+=" "),a+="Value: ["+d+"]");0===a.length&&(a="All Selected Cookies");$("#savedCookiesTitle").val(a);$("#savedCookiesTitle").css("width",370);$("#savedCookiesContainerDiv").attr("style","height:"+(popupHeight-100)+"px; overflow:auto;");$("#saveCookiesErrorSpan").html("");
aO();$("#saveCookiesDialogDiv").dialog("destroy").dialog({autoOpen:!1,width:460,modal:!0,buttons:{Close:function(){$(this).dialog("close")}}});$("#saveCookiesDialogDiv").dialog("option","title","Save/Restore Cookies");$("#saveCookiesDialogDiv").dialog("open")}function aK(){maxSavedCookies=localStorage[lsMaxSavedCookies];void 0===maxSavedCookies?aL(-1):maxSavedCookies=parseInt(maxSavedCookies,10)}
function aL(a){maxSavedCookies=a;localStorage[lsMaxSavedCookies]=maxSavedCookies}function aI(){aK();for(var a=0;a<=maxSavedCookies;a++)if(void 0===localStorage[a1(a)])return a1(a);aL(maxSavedCookies+1);return a1(maxSavedCookies)}function a1(a){return lsSavedCookies+"-"+a}
function sortSavedCookies(a,b){a=a.title.toLowerCase()+(new Date(a.saved)).getTime();b=b.title.toLowerCase()+(new Date(b.saved)).getTime();return a<b?-1:a>b?1:0}
function aM(){$("#saveCookiesErrorSpan").html("");var a=$("#savedCookiesTitle").val();if(0===a.length)$("#saveCookiesErrorSpan").html("Title is required.");else{for(var b=[],c=0,d;d=allCookies[c];c++)$("#"+cookieCheckBoxPrefix+c).attr("checked")&&b.push(d);0===b.length?$("#saveCookiesErrorSpan").html('Could not save. No cookies have been selected (checked) for saving.&nbsp;&nbsp;&nbsp;<a href="" id="selectAllCookiesAnchor">select all</a>'):(c=new Date,a={title:a,saved:String(c),savedTS:c.getTime(),
cookies:b},b=aI(),localStorage[b]=JSON.stringify(a),aO())}}
function aO(){$("#savedCookiesDiv").html("");var a="<table><tr><td></td><td><b>Title</b></td><td><b>Saved</b></td><td><b>Cookies</b></td><td><b>Delete</b></td></tr>";aK();for(var b=[],c=0;c<=maxSavedCookies;c++)if(void 0!==localStorage[a1(c)]){var d=JSON.parse(localStorage[a1(c)]);b.push({name:a1(c),title:d.title,saved:d.saved,cookieCount:d.cookies.length,isInco:"0"==d.cookies[0].storeId?!1:!0})}b.sort(sortSavedCookies);for(c=
0;d=b[c];c++){var f=1===d.cookieCount?"application.png":2===d.cookieCount?"application_double.png":"application_cascade.png";a+="<tr>";a+="<td"+(d.isInco?' class="inco"':"")+"><a class='restoreSavedCookiesAnchor' cookieName='"+d.name+"' href='' title='Restore Saved Cookies'><img src='"+f+"' class='move-icon-down'></a></td>";a+="<td><a class='restoreSavedCookiesAnchor' cookieName='"+d.name+"' href='' title='Restore Saved Cookies'>"+d.title+"</a></td>";a+="<td>"+String(d.saved).replace(/ GMT.+/,"")+
"</td>";a+="<td align='center'>"+bG(d.cookieCount)+"</td>";f=d.title.replace(/'/g,"'").replace(/"/g,"");a+="<td align='center'><a class='delete_session_anchor' cookieName='"+d.name+"' cookieTitle='"+f+"' title='Delete Saved Cookies'><img class='delete-session-img move-icon-down' src='tab_close_2.png' class='move-icon-down'></a></td>";a+="</tr>"}a+="</table>";0===b.length&&(a="<br/><br/>&nbsp;&nbsp;&nbsp;<i>No saved cookies were found.</i>");$("#savedCookiesDiv").append(a);$(".delete_session_anchor").hover(function(){$(this).children(".delete-session-img").attr("src",
"tab_close_2_hover.png")},function(){$(this).children(".delete-session-img").attr("src","tab_close_2.png")})}function az(a,b){confirmDeleteStoredCookies?by("Delete Saved Cookies","Are you sure you want to delete these Saved Cookies?<br/><br/>"+b,deleteSavedCookies,a,null):deleteSavedCookies(!0,a)}function deleteSavedCookies(a,b){a&&(localStorage.removeItem(b),aO())}
function bG(a){var b=(a+"").split(".");a=b[0];b=1<b.length?"."+b[1]:"";for(var c=/(\d+)(\d{3})/;c.test(a);)a=a.replace(c,"$1,$2");return a+b}function by(a,b,c,d,f){$("#confirmSpan").html("<br/>"+b);$("#confirmDiv").dialog("destroy").dialog({autoOpen:!1,width:460,modal:!0,buttons:{Yes:function(){c(!0,d,f);$(this).dialog("close")},No:function(){c(!1,d,f);$(this).dialog("close")}}});$("#confirmDiv").dialog("option","title",a);$("#confirmDiv").dialog("open")}
function aw(a){if(confirmRestoreStoredCookies){var b=JSON.parse(localStorage[a]);by("Restore Saved Cookies","Are you sure you want to restore these Saved Cookies?<br/><br/>"+b.title,restoreSavedCookies,a,null)}else restoreSavedCookies(!0,a)}function restoreSavedCookies(a,b){a&&chrome.extension.getBackgroundPage().ao(b,loadCookies)}
function ao(a,b){a=JSON.parse(localStorage[a]);if(void 0===a||void 0===a.cookies)$("#saveCookiesErrorSpan").html("Error restoring saved cookies.");else{for(var c=0,d;d=a.cookies[c];c++)bp(d);void 0!==b&&b()}}
function bp(a){var b="http"+(a.secure?"s":"")+"://"+a.domain.replace(/^\./,"")+a.path,c=a.expirationDate;restoreFixExpiration&&void 0!==c&&new Date(1E3*c)<new Date&&(c+=31556926);b={url:b,name:a.name,value:a.value,path:a.path,secure:a.secure,httpOnly:a.httpOnly,expirationDate:c,storeId:a.storeId};"."==a.domain[0]&&(b.domain=a.domain);chrome.cookies.set(b,function(){var a=chrome.runtime.lastError;a&&console.info("bp() Error:",a.message)})}
function aJ(){var a=new Date($("#newExpirationDatePicker").datepicker("getDate")),b=parseInt($("#newExpirationHours").val(),10),c=parseInt($("#newExpirationMinutes").val(),10),d=parseInt($("#newExpirationSeconds").val(),10);a.setHours(b);a.setMinutes(c);a.setSeconds(d);return a}
function aT(){aB();aa();aD();af();a3();bd();a7();aU();a9();bg()}
function bv(){$("#styleSelect").val(uiStyle);rememberFilter&&void 0!==filterDomain&&null!=filterDomain&&""!==filterDomain&&0<filterDomain.length&&"undefined"!==filterDomain&&$("#filterDomainInput").val(filterDomain);rememberFilter&&void 0!==filterName&&null!=filterName&&""!==filterName&&0<filterName.length&&"undefined"!==filterName&&$("#filterNameInput").val(filterName);rememberFilter&&void 0!==filterValue&&null!=filterValue&&""!==filterValue&&0<filterValue.length&&"undefined"!==filterValue&&
$("#filterValueInput").val(filterValue);var a="height:"+popupHeight+"px; overflow:auto;";$("#cookiesDiv").attr("style",a);a="height:"+(popupHeight-100)+"px; overflow:auto;";$("#detailsDialogueContainer").attr("style",a);$("#editDialogueContainer").attr("style",a);$("body").css("min-width",popupWidth);700===popupWidth?$("#filterDomainInput,#filterNameInput,#filterValueInput").css("width","120px"):750===popupWidth&&$("#filterDomainInput,#filterNameInput,#filterValueInput").css("width","140px")}
function bc(){$("input:button").button();$("#confirmDeleteCookiesCheckBox").attr("checked",confirmDeleteCookies);$("#confirmRestoreStoredCookiesCheckBox").attr("checked",confirmRestoreStoredCookies);$("#restoreFixExpirationCheckBox").attr("checked",restoreFixExpiration);$("#confirmDeleteStoredCookiesCheckBox").attr("checked",confirmDeleteStoredCookies);$("#rememberFilterCheckBox").attr("checked",rememberFilter);$("#heightSelect").val(popupHeight);$("#widthSelect").val(popupWidth);bH()}
function aB(){confirmDeleteCookies=localStorage[lsConfirmDeleteCookies];void 0===confirmDeleteCookies?aC(!0):confirmDeleteCookies=/^true$/i.test(confirmDeleteCookies)}function aC(a){confirmDeleteCookies=a;localStorage[lsConfirmDeleteCookies]=confirmDeleteCookies}
function aa(){confirmRestoreStoredCookies=localStorage[lsConfirmRestoreStoredCookies];void 0===confirmRestoreStoredCookies?ae(!0):confirmRestoreStoredCookies=/^true$/i.test(confirmRestoreStoredCookies)}function ae(a){confirmRestoreStoredCookies=a;localStorage[lsConfirmRestoreStoredCookies]=confirmRestoreStoredCookies}
function aD(){restoreFixExpiration=localStorage[lsRestoreFixExpiration];void 0===restoreFixExpiration?aE(!0):restoreFixExpiration=/^true$/i.test(restoreFixExpiration)}function aE(a){restoreFixExpiration=a;localStorage[lsRestoreFixExpiration]=restoreFixExpiration}
function af(){confirmDeleteStoredCookies=localStorage[lsConfirmDeleteStoredCookies];void 0===confirmDeleteStoredCookies?ah(!0):confirmDeleteStoredCookies=/^true$/i.test(confirmDeleteStoredCookies)}function ah(a){confirmDeleteStoredCookies=a;localStorage[lsConfirmDeleteStoredCookies]=confirmDeleteStoredCookies}
function a3(){filterDomain=localStorage[lsFilterDomain];void 0===filterDomain&&a4("")}function a4(a){filterDomain=a;localStorage[lsFilterDomain]=filterDomain}function bd(){filterName=localStorage[lsFilterName];void 0===filterName&&bf("")}function bf(a){filterName=a;localStorage[lsFilterName]=filterName}function a7(){filterValue=localStorage[lsFilterValue];void 0===filterValue&&a8("")}
function a8(a){filterValue=a;localStorage[lsFilterValue]=filterValue}function aU(){rememberFilter=localStorage[lsRememberFilterCloseTab];void 0===rememberFilter?aV(!0):rememberFilter=/^true$/i.test(rememberFilter)}function aV(a){rememberFilter=a;localStorage[lsRememberFilterCloseTab]=rememberFilter}
function a9(){popupHeight=localStorage[lsPopupHeight];void 0===popupHeight?bb(450):popupHeight=parseInt(popupHeight,10)}function bb(a){popupHeight=a;localStorage[lsPopupHeight]=popupHeight}function bg(){popupWidth=localStorage[lsPopupWidth];void 0===popupWidth?bh(750):popupWidth=parseInt(popupWidth,10)}function bh(a){popupWidth=a;localStorage[lsPopupWidth]=popupWidth}
function bH(){uiStyle=localStorage[lsUiStyle];void 0===uiStyle&&(uiStyle="start");$("#styleLink").attr("href","http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/"+uiStyle+"/jquery-ui.css")}
function bz(){aC($("#confirmDeleteCookiesCheckBox").attr("checked"));ae($("#confirmRestoreStoredCookiesCheckBox").attr("checked"));aE($("#restoreFixExpirationCheckBox").attr("checked"));ah($("#confirmDeleteStoredCookiesCheckBox").attr("checked"));aV($("#rememberFilterCheckBox").attr("checked"));bb($("#heightSelect").val());bh($("#widthSelect").val());
$("#statusSpan").html("Saved!");setTimeout(function(){$("#statusSpan").html("")},1E3)}function bA(){window.close()};
